### ISSUE TITLE
Disable all weekends

### ISSUE THREAD

**Issue by CristhianUNSa** [nazar-pc/PickMeUp#100]
I want to disable all weekends on all my calendars (12 months displayed), so my employee's vacations only count business days . Is this possible ?
Thanks in advance!

**Comment by nazar-pc** [comment]
Yes, you can use `render` event for this:
```javascript
...
    render : function (date) {
        if (date.getDay() == 0 || date.getDay() == 6) {
            return {disabled : true};
        }
        return {};
    }
...
```

But this will only make them impossible to select, if you take date range - you'll need to remove weekends from total number of days in range manually.

**Comment by CristhianUNSa** [comment]
I've already done this, thanks. And total number of days are total range selected days including weekends like you said, but doesn't matter. Cheers!
