### ISSUE TITLE
bind click event

### ISSUE THREAD

**Issue by ArvindhS** [nazar-pc/PickMeUp#102]
How to bind click event in pickmeup Plugin?

**Comment by nazar-pc** [comment]
What do you mean by click event? Can you describe your use case?

**Comment by ArvindhS** [comment]
I want  to highlight few particular dates (ie) few days in week.and i want to choose the date in random manner.Also i want to find the difference berween the selected date and the current date.(ie) the current day. By using "change" callback i found the difference but can't highlight the dates.

**Comment by nazar-pc** [comment]
To highlight the date you can apply additional class to day element using `render` event.

**Comment by ArvindhS** [comment]
Actually i want to highlight some days in the month calendar(ie) 1/1/16 - 5/1/16.And also i want to select the dates in random manner and want to find the difference between selected date and current date (ie) today. i solved that difference by using "change" callback but i can't able  to highlight some dates.

**Comment by nazar-pc** [comment]
I already told you how to highlight days.
About dates selection - you can use `set_date` method.

**Comment by ArvindhS** [comment]
Can u now explain now?

**Comment by nazar-pc** [comment]
```javascript
$(...).pickmeup({
...
  render : function (date) {
    if (highlight_date(date)) {
      return {class_name : 'day-highlighted'};
    }
  }
...
});
```

**Comment by ArvindhS** [comment]
can i removeClass using render ?

**Comment by nazar-pc** [comment]
No, `render` is called on each day every time PickMeUp is updated in any way. So generally just set right class, you never need to remove it since it will be removed on refresh automatically.

**Comment by ArvindhS** [comment]
yeah boss i will try.I will say the output tommorrow because here in my system,I didn't have that project  right now .its in my office pc.
Thanks for rectifying my doubts.

**Comment by ArvindhS** [comment]
I cannot able to highlight dates when i select a date.
My code is:
$('.datePick').pickmeup({
            flat : true,
            select_month : false,
            select_year : false,
            first_day : 0,
            min : '<?php echo date('m-d-y',strtotime($first_date));?>',
            max : '<?php echo date('m-d-y',strtotime($last_date));?>',
            format:'m-d-y',
            trigger_event : 'click',
change : function(date){
                var dateSelected=date;
                //$(".pmu-dateSelected").prevUntil('.pmu-disabled').css('background-color','yellow');
                $('.cal_partial_date').text(moment(date,"MM-DD-YYYY").format('ddd[,] ll'));
                var currentFuture = moment(date,"MM-DD-YYYY");
                var currentStart = moment('<?php echo date('m-d-y');?>',"MM-DD-YYYY");
                var currentDiffDate = currentFuture.diff(currentStart,'days');
                $('.cal_partial_date_no').text((currentDiffDate));
            },
            render :function(date){
                if ($.inArray(date.getTime(), dateTable) > -1){
                    return {
                        class_name : 'highlight'
                    }
                }


            }
        });
        
        $('.datePick').pickmeup('set_date','<?php echo date('m/d/y',strtotime($last_date));?>');
        
        $('.pmu-dateSelected').prevUntil('.pmu-disabled').css('background-color','yellow');

**Comment by ArvindhS** [comment]
I cant able to highlight from the date which i clicked to my current date. Using "render" i can able to add only classes for the unchanged days.

**Comment by nazar-pc** [comment]
`render` is called on each day on each update. You can add classes to all visible days, just write correct `highlight_date` function from my example above

**Comment by ArvindhS** [comment]
Thanks Boss,Now it works.
