### ISSUE TITLE
npm support?

### ISSUE THREAD

**Issue by yazonnile** [nazar-pc/PickMeUp#104]
Hi, Nazar!
It would be very nice, if you`ll add this plugin on npm!

**Comment by nazar-pc** [comment]
Just published as is: https://www.npmjs.com/package/pickmeup
In future I'll likely add some tweaks to it.
Is it fine for you?

**Comment by yazonnile** [comment]
Yes. It's great.
Thx!

**Comment by yazonnile** [comment]
Hi, again. Sorry for disturbing.
But npm module need minor fix with adding entry point
![...](http://screen.w3.ua/Feb16/1390921387.jpg)

thx!

**Comment by nazar-pc** [comment]
I'll add it in next release, anyway you'll include that file manually on frontend.

**Comment by yazonnile** [comment]
Actually not. I use this file like module - require('pickmeup')
It's much simplier )

**Comment by nazar-pc** [comment]
Just released 2.9.0

**Comment by yazonnile** [comment]
thx for quick response
