### ISSUE TITLE
Year view

### ISSUE THREAD

**Issue by wheelq** [nazar-pc/PickMeUp#105]
How do I display 12,13 months on one page + enable selector? is it possible?

**Comment by nazar-pc** [comment]
Can you elaborate a bit what do you need exactly? Current question is pretty abstract.

**Comment by wheelq** [comment]
Either this:

[http://www.iworkcommunity.com/system/previews/images/000/000/597/original/2010_calendat_year_view_gantt_.jpg?1376526066]

or this view:

[http://www.devcomponents.com/dotnetbar/img/CalendarYearView1.png]

**Comment by nazar-pc** [comment]
First is definitely not supported, second is pretty doable when you specify `calendars : 12` and reduce parent container width so that it will break down into 3 rows of calendars. However, common header with arrows right and left you'll need to make yourself.
