### ISSUE TITLE
Add event

### ISSUE THREAD

**Issue by wheelq** [nazar-pc/PickMeUp#106]
Is there an option for adding notes/popups when I click on a date or selection of dates?

**Comment by nazar-pc** [comment]
There is no such event, but as usual you can use `$(...).on(...)` to track clicks. About selection - there is `change` event.

**Comment by ssheduardo** [comment]
Please, some example.

**Comment by nazar-pc** [comment]
Click is regular click, just take a look at [jQuery docs](https://api.jquery.com/on/).
About change event there was few questions and answers in issues already, for instance this one: https://github.com/nazar-pc/PickMeUp/issues/87#issuecomment-128334958

**Comment by lenchik-ponchik** [comment]
Click не работает даже если вешать на документ.

**Comment by nazar-pc** [comment]
@lenchik-ponchik:
1) English
2) Simplified demo where it doesn't work
