### ISSUE TITLE
How to only show 5 week?

### ISSUE THREAD

**Issue by ssheduardo** [nazar-pc/PickMeUp#107]
How to only show 5 week?
In this example not show the last week [7, 8 ,9 10,11,12,13]
![Image of calendar](http://i.imgur.com/QUU08ki.png)

**Comment by nazar-pc** [comment]
There is no way to do this, because some months require 6 rows:
![2016-02-10 00-27-17](https://cloud.githubusercontent.com/assets/928965/12934191/15db3964-cf8d-11e5-8b07-2c729dc3e5dd.png)

**Comment by ssheduardo** [comment]
Ok, thanks.
Good jobs!!!
My partner has been responsible for customizing styles.

![captura de pantalla 2016-02-10 a las 0 30 16](https://cloud.githubusercontent.com/assets/1160138/12934318/04314dec-cf8e-11e5-831a-b653866bbc7d.png)

**Comment by nazar-pc** [comment]
Nice :+1: 
Can I close this issue?

**Comment by ssheduardo** [comment]
yes.
