### ISSUE TITLE
Disable calendar 'jumping'

### ISSUE THREAD

**Issue by wheelq** [nazar-pc/PickMeUp#108]
How do I disable calendar 'jumping', because whenever I make a new selection from the next month, months suddenyl switch in the viewing area. I need them to be static. Just like on this website (is this your calendar?) http://www.eyecon.ro/datepicker/

Also, how do I disable days from the previous/next month in the current month view?

**Comment by nazar-pc** [comment]
I think what you're asking is #41, it has PR suggested, but was not merged yet, you can try to apply it yourself.

http://www.eyecon.ro/datepicker/ is a datepicker on which PickMeUp is based, it was hugely rewritten with many bugs fixed and features added.

> Also, how do I disable days from the previous/next month in the current month view?

This is another issue (I'll appreciate if you put different questions in different issues), you can control disabled dates using `min`/`max` options and/or `render` event.

**Comment by wheelq** [comment]
thank you so much
