### ISSUE TITLE
Is it possible to have nice fofmat date in visible input field

### ISSUE THREAD

**Issue by cretace** [nazar-pc/PickMeUp#109]
Can I set it so my visible input field shows a nicely formatted date in  j M Y format
- for instance: 1 Jan 2016

If I put 1 Jan 2016 in the input field and specify format as j M Y then calendar reverts to today
(I will be parsing inputs with PHP to save to database)

**Comment by nazar-pc** [comment]
Yes, there is `format` option for this

**Comment by cretace** [comment]
very fast reply - thanks!
I am setting format :
 $('.datep :input').pickmeup({
    	        format:'d M Y',
		hide_on_select: true
	});

**Comment by nazar-pc** [comment]
Try this format instead: `d b Y`. It should work back and forth.

**Comment by cretace** [comment]
Great - works perfectly - thanks!
