### ISSUE TITLE
default_date, date, 

### ISSUE THREAD

**Issue by gzhegow2all** [nazar-pc/PickMeUp#110]
Image
https://i.gyazo.com/ba5368ad114be15d29704b1dff00997e.png

Please check, it's not working.
When load i have my default value, when i click at the field the pickmeup is loading, and replace date to MIN, i feel it as ignoring date and default_date. if i set default_date to false, the date field is ignored, even if i remove default value and set "new Date()".

i checked when min is bigger than selected, and converselly - still not working

as i think, it may be works next:
- min/max - is only limiters
- date - is default date when run .pickmeup() method to field (not when click at field)
- default_date - not required, might to be deleted
- if (date > min) && (date < max) = use date, otherwise, respectively
- if date is defined in field, is using date from the field by parsing it by "format" field
- if date is not defined use default (new Date())

**Comment by nazar-pc** [comment]
Can you prepare live demo, please? I would be easier to debug with minimal reliable reproducible example.

**Comment by gzhegow2all** [comment]
http://www.fakeltour.ru/widget/

2016-03-10 0:46 GMT+03:00 Nazar Mokrynskyi <notifications@github.com>:

**Comment by nazar-pc** [comment]
Looks like there is some bug with date parsing when format doesn't have any separators.
Here is kind of example I was asking for: https://jsfiddle.net/z4fmvuzb/199/

**Comment by gzhegow2all** [comment]
lol, my code creates correct Date string about 1 may, i give Date object to
pickmeup

2016-03-10 0:53 GMT+03:00 Nazar Mokrynskyi <notifications@github.com>:

**Comment by nazar-pc** [comment]
As workaround you can open pickmeup manually on click, handle change event and set date when necessary. This is awkward, but it will help you to get job done until proper fix released.

**Comment by gzhegow2all** [comment]
ok i correct, still not working, date is dropping to today.
http://take.ms/MkP7O

2016-03-10 0:53 GMT+03:00 Nazar Mokrynskyi <notifications@github.com>:

**Comment by nazar-pc** [comment]
Yes, this is a bug, use workaround instead

**Comment by gzhegow2all** [comment]
ok, thx for your attention.

**Comment by nazar-pc** [comment]
I don't think we'll support format without separators. For such cases I recommend to use events and manage things manually.
