### ISSUE TITLE
Sample 'local' use

### ISSUE THREAD

**Issue by SpartakN** [nazar-pc/PickMeUp#112]
Could you show some sample use local (for example, a russian). How is it necessary to prepare object for `local` option? Maybe are there ready translations for various languages?

**Comment by Icemo** [comment]
What is it?

**Comment by nazar-pc** [comment]
It is the same as in source code: https://github.com/nazar-pc/PickMeUp/blob/master/js/jquery.pickmeup.js#L85
You can just copy it, modify and pass as an option during initialization or modify `$.pickmeup.locale` to apply it to page globally.

**Comment by Icemo** [comment]
Can you tell me its use?

**Comment by Icemo** [comment]
Is for me?

**Comment by nazar-pc** [comment]
It was for topic starter.
It is used for localization, to translate interface into language other than English if you need to.

**Comment by Icemo** [comment]
starter？Not the date control?

**Comment by SpartakN** [comment]
Russian localization:
```
$('.date').pickmeup({
  local: {
			days		: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
			daysShort	: ['Вск', 'Пнд', 'Втр', 'Срд', 'Чтв', 'Птн', 'Сбт', 'Вск'],
			daysMin		: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
			months		: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
			monthsShort	: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек']
         }
});
```
Thank you for your widget!

**Comment by Icemo** [comment]
Sorry for the first time to play this, don't know much about.

**Comment by SpartakN** [comment]
I was wrong to have used `local` instead of `locale`. Now all my posts corrected.
