### ISSUE TITLE
Calendar start date should be on the current month

### ISSUE THREAD

**Issue by b3taboy** [nazar-pc/PickMeUp#114]
Hello,

I would like to know what is the setting for making the calendar to start with the current month instead showing starting with the previous one.
https://www.dropbox.com/s/anjl19w2klutr0n/Screenshot%202016-05-14%2013.18.23.png?dl=0

Thank you

**Comment by nazar-pc** [comment]
It tries to adjust calendars so that current months is in the center. I believe, options you're looking for should be covered by #79, but it is not ready to be merged (however, you can try and use it if it suits you well in its current form).

**Comment by b3taboy** [comment]
Ok I will close this issue. Thank you for the quick reply.
