### ISSUE TITLE
Как подключить input к multiple

### ISSUE THREAD

**Issue by zaza41rus** [nazar-pc/PickMeUp#117]
Понравилась ваша работа и в особенности выбор - multiple :+1: .
Искал именно такую функцию у календарей.

_Без проблем только первое заработало и передает информацию:_
```
<section>
	Input
	<article>
		<input name="data-multiple" type="text" value="01-01-2014">
	</article>
</section>
```

Я извиняюсь за уровень своих познаний, уже все перечитал здесь, но так и не понял

**как подключить** 
> `<div class="multiple"></div>`

**к** 
> `<input name="data-multiple" type="text">`

**?**

**Comment by nazar-pc** [comment]
Можете сделать демку где одно работает, а другое нет?
Пример есть в readme.

**Comment by zaza41rus** [comment]
Я на столько ущерблен в этом, что видимо даже не могу объяснить )
Работает все... не получается передать данные из 
> `<div class="multiple"></div>`

в обработчик.
Не понимаю, куда должен прописать атрибут name="data"
[Пример](http://jsfiddle.net/zaza41rus/z4fmvuzb/229/)

**Comment by nazar-pc** [comment]
Мда, наконец понял что вам нужно :smile: 
Вы хотите использовать inline календарь и отправлять выбранную дату вместе с формой, правильно же?

Здесь PickMeUp ни при чем. Стандартные формы отправляют только `<textarea>`, `<input>` и по-моему всё.

Для того чтобы работало как вы хотите нужно:
* добавить в форму `<input type="hidden" name="DATE-2">`
* подписаться на событие [change](https://github.com/nazar-pc/PickMeUp#change-formatted_date)
* когда событие срабатывает менять содержимое `input[name=DATE-2]`

**Comment by zaza41rus** [comment]
В общем, пока чет не выходит :(

Подскажите, не смогли отыскать
- в какую переменную попадают выбранные даты?
- можно ли их поместить в массив?

**Comment by nazar-pc** [comment]
Есть же [специально для этого предназначенный метод](https://github.com/nazar-pc/PickMeUp#get-date)
