### ISSUE TITLE
Keeps appending pickmeup

### ISSUE THREAD

**Issue by volomike** [nazar-pc/PickMeUp#122]
I was just going to say that at the bottom of your jquery.pickmeup.js file where you have this line...

```
pickmeup.appendTo(document.body);
```

...you're not checking to see if you already have that added. This came up for me when I was using the .load() call in jQuery to load right-pane content into a page -- it kept adding the pickmeup entry to the bottom of the BODY. The fix was to change that line to these three lines:

```
if ($('.pickmeup').length < 1) {
	pickmeup.appendTo(document.body);
}
```

**Comment by nazar-pc** [comment]
It should only happen when you add PickMeUp to `<input>` element. It doesn't happen in `flat` mode.
Also, you can always move it anywhere you like after initialization.
