### ISSUE TITLE
Вопросы по плагину

### ISSUE THREAD

**Issue by kzpromo** [nazar-pc/PickMeUp#123]
Добрый день, очень нравится Ваш плагин
Хочу узнать как получить выбранные дни в режиме **mode: "range"**?
Я хочу, чтобы каждый выбранный день через **ajax** можно было записать в Базу данных

Буду благодарен за помощь ;)

**Comment by nazar-pc** [comment]
Попробуйте https://github.com/nazar-pc/PickMeUp#get-date

**Comment by kzpromo** [comment]
@nazar-pc я не могу понять как происходит обработка события
Надо обрабатывать событие click или же get_date?


```
$(".3-calendars").pickmeup("click", function(e){
        alert($(".3-calendars").pickmeup("get_date", true));
});
```

или же 

```
$(".3-calendars").pickmeup({
        flat: true,
        mode: "range",
        click: function(e){
             alert($(".3-calendars").pickmeup("get_date", true));
        }
    });
```

или 

```
$(".3-calendars").pickmeup({
        flat: true,
        mode: "range",
        get_date: function(true){
             alert($(".3-calendars").pickmeup("get_date", true));
        }
    });
```

Помогите решить проблему

**Comment by nazar-pc** [comment]
Когда вы их хотите получить?
Если при изменении - есть событие `change`:
```javascript
$(...).pickmeup({
    change : function (formatted_date) { // Тут форматированная дата
...
});
```
Если же в произвольное время (в том числе в событии `change` если нужна неформатировання дата) - тогда:
```javascript
$(...).pickmeup('get_date', true);
```

**Comment by kzpromo** [comment]
@nazar-pc спасибо, понял теперь.
А нет опции, чтобы он создавал массив каждого дня, который находится в интервале, получается он берет 2 даты (от и до)?

**Comment by nazar-pc** [comment]
Для диапазона две даты, для других режимов по-другому. Одним циклом можете при желании получить массив, ничего сложного.
