### ISSUE TITLE
Лишняя неделя

### ISSUE THREAD

**Issue by mbaev** [nazar-pc/PickMeUp#124]
Можно ли сейчас как-то исключить последнюю неделю из следующего месяца? Мне она кажется лишней. Я такого не встречал.
![2016-08-05_22-33-34](https://cloud.githubusercontent.com/assets/6450526/17446940/d22f8114-5b5c-11e6-9d7b-4ac66a406f1e.jpg)

**Comment by nazar-pc** [comment]
Рекомендую смотреть ответы на другие вопросы здесь, на GitHub (такой уже задавали), а ещё было бы здорово задавать на английском, чтобы больше людей могли прочесть, понять, и не задавать в будущем одно и то же.

По сути: нет, нельзя, потому что в других месяцах не хватит места и календарь будет постоянно прыгать. Посмотрите, куда попадет 31 число, если в первое начнется не в понедельник, а в воскресенье на той же неделе?

**Comment by mbaev** [comment]
Понял ответ на первый вопрос. Спасибо.

**Comment by nazar-pc** [comment]
Никогда не задавайте два вопроса в одном! Это сбивает с толку и дико неудобно при повторном поиске, создавайте новый вопрос.

**Comment by mbaev** [comment]
Ок, очень быстро отвечаете. Я не успел отредактировать. Сейчас создам еще вопрос.
