### ISSUE TITLE
Использование callback disabled

### ISSUE THREAD

**Issue by AliveDD** [nazar-pc/PickMeUp#127]
Прошу добавить пример использования callback disabled, в момент когда я по стороннему событию хочу сделать недоступным тот или иной день.

P.S. Планируется ли описание (example) для быстрой интеграции: webpack + jquery + pmu?

**Comment by nazar-pc** [comment]
Да, примеров нужно будет добавить.
Нет, не планируется. Если желаете - можете добавить страничку в wiki, но желательно на английском.

И будьте добры, давайте одну тему в одном issue.

**Comment by AliveDD** [comment]
> Да, примеров нужно будет добавить.
И все-таки — как это сделать?

**Comment by nazar-pc** [comment]
Рекомендую пользоваться поиском, на некоторые вопросы уже есть ответы, к примеру, вот этот: https://github.com/nazar-pc/PickMeUp/issues/100

**Comment by AliveDD** [comment]
этот пример работает при рендеринге календаря, а нам необходимо деактивировать дату в по стороннему событию, которое может сработать после рендера

что то вроде:

    $('button').on('click', function() {
        $('.date').pickmeup('disable_date', '16.08.2016');
    }

**Comment by nazar-pc** [comment]
Обновите его, это приведет к повторному рендерингу: https://github.com/nazar-pc/PickMeUp#update-datepicker

**Comment by AliveDD** [comment]
страшная конечно конструкция, но спасибо!
<img width="692" alt="screen shot 2016-08-17 at 11 09 30" src="https://cloud.githubusercontent.com/assets/5255027/17729099/8487dcb6-6473-11e6-98f7-5b8ae08717b7.png">
