### ISSUE TITLE
babel error

### ISSUE THREAD

**Issue by AliveDD** [nazar-pc/PickMeUp#128]
В проекте с вебпаком подключен babel, включающий es2015 функционал
плагин PMU подключен через require('./vendor/pickmeup.js');

при смене дня в календаре нажатием мыши в консоль прилетает ошибка:

<img width="738" alt="pmu" src="https://cloud.githubusercontent.com/assets/5255027/17729547/c7012c08-6475-11e6-94d4-eb7b7ce01a0d.png">

без babel ошибки нет

**Comment by nazar-pc** [comment]
Не использую babel, поэтому сказать что-то затрудняюсь.
Как вариант я бы, конечно, рекомендовал грузить через RequireJS вместо безусловного подключения как у вас, но такое использование тоже имеет право на жизнь.
Если найдете причину и исправите - буду рад принять PR.

**Comment by nazar-pc** [comment]
Можете попробовать сборку из master ветки? Там было достаточно много изменений, есть шанс что эта ошибка пропадет.

**Comment by AliveDD** [comment]
попробую сегодня-завтра

**Comment by nazar-pc** [comment]
Получилось перепроверить?
Если всё ещё актуально - было бы здорово если вы сделаете демо-репозиторий чтобы я воспроизвел ошибку у себя.
