### ISSUE TITLE
Сбрасываются заблокированные даты

### ISSUE THREAD

**Issue by kzpromo** [nazar-pc/PickMeUp#130]
Добрый день, при загрузке страницы, загружается список дат для того чтобы заблокировать их (render). При событии (change), сбрасываются блокированные дни, в чем может быть проблема?

Календарь (.3-calendars)

Пример кода

```
$(".3-calendars").pickmeup({
        flat: true,
        mode: "range",
        format : "Y-m-d",
        separator:";",
        render: function(date) {
            var id = $(this).attr("data-stock_id");
            var year = date.format("yyyy");
            var month = date.format("mm");
            var day = date.format("dd");
            var item = year + "-" + month + "-" + day;
            
            if(!yearmonth[year+month]) {
                load_reservation(id, year, month, null, function(result){
                    array[id] = result;
                    yearmonth[year+month] = 1;
                });
            }           
            if ($.inArray(item, array[id]) > -1){
                return {
                    disabled   : true,
                    class_name : "disabled"
                }
            }
        },
        change: function(date){
            var id = $(this).attr("data-stock_id");
            if(date[0]!=date[1]){
                reserv_interval(id, date[0], date[1]);
            }
        }
    });
```

**Comment by nazar-pc** [comment]
Будьте добры, сделайте демку. А ещё попробуйте код из ветки master, там недавно были изменения, которые могут повлиять на данное поведение.

**Comment by kzpromo** [comment]
на сайте http://kfrental.kz/ добавьте товар в корзину, перейдите к корзине, там будет календарь! там будет видно, на jsfiddle позже постараюсь залить

**Comment by nazar-pc** [comment]
Что-то я так и не понял. jsfiddle очень поможет, так как я сразу смогу проверить работает ли исправление.

**Comment by kzpromo** [comment]
@nazar-pc на jsfiddle не получается залить пример, не могли бы вы посмотреть на рабочем сайте или как можно напрямую связаться с Вами?
Плюс появилась ошибка
```
TypeError: c is undefined
	

e,f){f[e]=l(g.trim(a),b,d,c)}),e;e=c.monthsShort.join(")(")+")("+c.months.join("...

	
jquery.....min.js (строка 19, столбец 34)
```

**Comment by nazar-pc** [comment]
Что именно не получается? В readme есть пример, просто измените его и укажите что сделать чтобы воспроизвести ошибку.
Вы используете версию из master ветки?
В каком браузере ошибка?
Используйте для отладки неминифицированную версию, в ней воспроизводится ошибка?

**Comment by kzpromo** [comment]
при загрузке список блокированных дат встает нормально, стоит нажать на календарь, они исчезают
так же после обновления из ветки мастер появилась ошибка

[TypeError: c is undefined
e,f){f[e]=l(g.trim(a),b,d,c)}),e;e=c.monthsShort.join(")(")+")("+c.months.join("...
jquery.....min.js (строка 19, столбец 34)](url)

![1](https://cloud.githubusercontent.com/assets/10184174/18124255/4752a3be-6f93-11e6-97b9-6b2b8185938e.png)
![2](https://cloud.githubusercontent.com/assets/10184174/18124254/4750c5c6-6f93-11e6-9a6f-26068942cff7.png)

**Comment by nazar-pc** [comment]
Я вообще на сайте не вижу календаря. Если не будет JSfiddle примера я не смогу помочь. Опять таки, если не возьмете неминифицированную версию я не смогу вам помочь.

**Comment by kzpromo** [comment]
@nazar-pc надо добавить товар в корзину, затем перейти в корзину, там появится календарь

**Comment by nazar-pc** [comment]
Я это сделал, там не PickMeUp, а что-то совсем другое. И в любом случае дебажить там нормально не получится.

**Comment by nazar-pc** [comment]
Обновил код в ветке master, ошибки с `undefined` быть больше не должно.

**Comment by nazar-pc** [comment]
Ну так что по этому вопросу?
