### ISSUE TITLE
show() actually not show datepicker

### ISSUE THREAD

**Issue by we2seek** [nazar-pc/PickMeUp#135]
Sorry for my incompetence, but I can't make button "Show calendar" works. Please, check out code example on [JSFiddle](https://jsfiddle.net/we2seek/bLftk8b0/19/).

**Comment by nazar-pc** [comment]
Very strange, `setTimeout(pickmeup(calendar).show)` works, but `pickmeup(calendar).show()` doesn't.

**Comment by nazar-pc** [comment]
Very interesting. Even though `.show()` method was called in `click` event handler, `click` event handler registered in `.show` method was also fired, closing datepicker immediately.
Should be fixed in cee5c4a.

**Comment by nazar-pc** [comment]
Thank you for reporting with demo, appreciate it!
Working on #136 right now.
