### ISSUE TITLE
Range selection impossible

### ISSUE THREAD

**Issue by we2seek** [nazar-pc/PickMeUp#136]
I have used range mode with oldest version PMU (~2.9.0) and first click on calendar was for beginning of range and second one — for end of range. But now, calendar disappears after the first click and range's start and end equal to the same date with no chance to change it. Please, check it [here](https://jsfiddle.net/we2seek/9c5jqco1/11/).
I know I use Angular JS in this example, but without it PMU's behavior the same.

**Comment by nazar-pc** [comment]
Should be fixed in 2cca2a8, new version 3.0.5 with this fixes is already released.
