### ISSUE TITLE
Подскажите как установить начальный год?

### ISSUE THREAD

**Issue by inververs** [nazar-pc/PickMeUp#139]
Как сделать что бы календарик открывался с момента выбора годов, где то 50 лет назад?
Сейчас у меня открывается с года  2010 - 2021, а надо с 1960 - 1971
Спасибо.
Вот мой конфиг.
```javascript
    $('.js-datepicker').pickmeup({
        position: 'top',
        hide_on_select: true,
        first_day: 0,
        format: 'Y-m-d',
        view : 'years',
        default_date: false
    });
```

**Comment by nazar-pc** [comment]
Укажите min/max опции или соотвествующую дату в опции date

**Comment by inververs** [comment]
`date: new Date(1960, 0, 1)` 
Так сделал, у меня была старая версия, там не работало, обновился и дело пошло.
Жалко что в IE11 ругается на Объект не поддерживает свойство или метод "repeat"
`element.innerHTML = options.instance_template(options).repeat(options.calendars);`

**Comment by nazar-pc** [comment]
Да, что-то не досмотрел что IE не умеет этот метод.
Новая версия PickMeUp сильно изменилась, многие недочёты были исправлены.

**Comment by nazar-pc** [comment]
Только что выпустил версию 3.0.6, проверьте работает ли.

**Comment by inververs** [comment]
Да работает, но в какие версиях IE оно будет работать?

**Comment by nazar-pc** [comment]
Должно в IE10+ (в целом). Конкретно этот участок переписан так, что IE5 скушает.

**Comment by inververs** [comment]
Понятно, спасибо за быстрое исправление.

**Comment by nazar-pc** [comment]
Если будут ещё какие-то проблемы - пишите:)
