### ISSUE TITLE
Prevent change

### ISSUE THREAD

**Issue by MadanBhandari** [nazar-pc/PickMeUp#140]
Hi Nazar,
How can I prevent change date from user? I want to set date by `set_date()` and not to be changed by user. When I use `disabled : true` and `selected: true`, It does not highlight the selected date/range.

**Comment by nazar-pc** [comment]
You can prevent clicks on instance like this: https://jsfiddle.net/3w7a6ato/

**Comment by MadanBhandari** [comment]
Thank you, it's solved now.
