### ISSUE TITLE
Render weekend days and holiday days

### ISSUE THREAD

**Issue by pararrayos** [nazar-pc/PickMeUp#146]
Hi Mr. Mokrynskyi. I'm using your fabolous calendar and I'm facing a minor problem.

I'm using **render** to make weekend days un-selectables, so I'm coding this:

```
...
render : function (date) {
		if (date.getDay() % 6 == 0) {
			return {disabled : true};
		}
               return {};
            }
...
```
_Note: three dots just mean more code before and after_

This works fine. But now I want to make holidays days un-selectables too, so I'm trying with this:

```
var holidayArray = [
        new Date('whateverday').getTime(), 
        new Date('whateverday').getTime(), 
       etc...]
...
render : function (date) {
		if (date.getDay() % 6 == 0) {
			return {disabled : true};
		}
 		for (var h = 0; h < holidayArray.length; h++) {
			if (holidayArray[h] == date.getTime()) {
				return {disabled : true};
			}
		} 
		return {};
	   }
...
```
And now weekend days are still unselectables (as desired) but holiday days' piece of code isn't working. Is there any 'restriction' or something like that in using a _for_ loop inside render?

Thanks :)

**Comment by nazar-pc** [comment]
There is no such limitation, any function is allowed there.
Try to use debugger in Dev Tools, just put breakpoint on the line inside of the loop to see if it is working and if not, then why. You can also run it line by line and see what exactly values are compared.

**Comment by pararrayos** [comment]
I found it. There was a missmatch among _new Date('whateverday').getTime()_ and _date.getTime()_. Now it works. Thank you anyway.
