### ISSUE TITLE
show/hide calendar input

### ISSUE THREAD

**Issue by MadanBhandari** [nazar-pc/PickMeUp#147]
Hi,
I am trying to show/hide calendar input. I mean If user click on input without selecting date, calendar should be hide if shown or vice-versa.

```
pickmeup('input.check-in-date', {
      position       : 'top',
      class_name		 : 'dt1',
      default_date   :  false,
      prev           : '<i class="fa fa-angle-left"></i>',
      next           : '<i class="fa fa-angle-right"></i>',
      hide_on_select : true,
      render : function (date) {
        if (date < now) {
          return {disabled : true, class_name : 'date-in-past'};
        }
        return {};
      }
    });
```

**Comment by nazar-pc** [comment]
Sorry, but I do not quite understand what do you need.
Can you describe it step by step or elaborate somehow in more details?

**Comment by MadanBhandari** [comment]
Sorry for late, I am trying to close/hide calendar on click input field without selecting date. As like `hide_on_select` for hiding after selection but I want to hide without selecting date.

**Comment by nazar-pc** [comment]
Did you try `hide` method for this?

**Comment by MadanBhandari** [comment]
Yeah, but how can I trigger this event `hide()`, that element is already bind on click event.

**Comment by nazar-pc** [comment]
Still can't quite understand what you need. `hide` method is separate from `click` event, it can be used directly.
Can you describe step by step what are you doing (or want to do), then what happens and what did you expect to happen instead. Or even better, prepare some demo on jsfiddle or jsbin to describe the question.

**Comment by MadanBhandari** [comment]
I want to do is toggle show/hide on click (input - without selecting date).

**Comment by nazar-pc** [comment]
Then you can subscribe to `click` event, suppress original even handler, and show/hide as you like.
Here is demo: https://jsfiddle.net/e70LyyL4/

**Comment by MadanBhandari** [comment]
This is exactly what I needed but It's not working on Chrome (v 52.0.xx), and working on Firefox.

**Comment by nazar-pc** [comment]
This one should work in all browsers: https://jsfiddle.net/e70LyyL4/1/

**Comment by nazar-pc** [comment]
Also I don't think `getPreventDefault()` comes from PickMeUp

**Comment by MadanBhandari** [comment]
same issue on fiddle you shared, check that on Chrome (v 52.0.xx) too.

**Comment by nazar-pc** [comment]
Works fine for me in Chromium Nightly 55.0.2880.0.
Anyway, you get the idea.

**Comment by MadanBhandari** [comment]
No, I didn't get what's the problem, I am beginner in JS.
I am facing same problem in **Chromium	52.0.2743.116 (Developer Build) Built on Ubuntu**

**Comment by nazar-pc** [comment]
Well, I gave you the code which works for me.
If it doesn't work for you, I can't fix it, since:
* I can't reproduce an issue
* this is not about PickMeUp itself, so this is your job, not mine

**Comment by MadanBhandari** [comment]
Thanks for your advise and time, I will look into this.
