### ISSUE TITLE
Ошибка в консоли если нету инпута

### ISSUE THREAD

**Issue by BazMaster** [nazar-pc/PickMeUp#148]
Если на странице нету инпута, то в консоль **Google Chrome** выходит следующая ошибка:
`Uncaught TypeError: Cannot read property '__pickmeup' of null`

А в Firefox в консоли следующее:
`TypeError: target is null`
`pickmeup.js:1188:7`

Такое бывает, когда датапикер используется на одной или нескольких страниц, а js-код вписан в общий для всего сайта js-файл.

Приходится вставлять скрытый инпут на всех страницах, чтобы ошибка не появлялась.

Демка с воспроизведённой ошибкой: https://jsfiddle.net/bazilio100lei/zo7553oh/2/

**Comment by nazar-pc** [comment]
Есть такое, спасибо.
Пока можете обойти это следующим образом:
```javascript
var element = document.querySelector('input');
if (element) {
  pickmeup(element, {
    position       : 'right',
    hide_on_select : true
  });
}

**Comment by nazar-pc** [comment]
Исправлено в 4adb1aa
