### ISSUE TITLE
Date time format

### ISSUE THREAD

**Issue by sachin0606** [nazar-pc/PickMeUp#151]
Hi Nazar, 

tried to add the format like 'dd-M-yyyy' but unable to get the result, 
where as i wanted to display date format like - '01-Jan-2016'

as you said Date format (aAbBCdeHIjklmMpPsSuwyY are supported) but its not working as expected.

**Comment by nazar-pc** [comment]
Add, please, a demo with what you've got so far on jsfiddle or jsbin.
