### ISSUE TITLE
Error at destroying the pickmeup calendar

### ISSUE THREAD

**Issue by mystyroi** [nazar-pc/PickMeUp#153]
Hi,

When i try to suppress the pickmeup, i've used the destroy function destroy() on addEventListener('DOMContentLoaded',...) block :

`pickmeup('.date').destroy(); (I've initialized well a pickemeup calendar)`

The error is : 

`Uncaught TypeError: Cannot read property 'indexOf' of undefined`

I want to destroy my calendar to make it reappear each time my first calendar is updated. I want to do this because once the pickemup object is created, its parameter are impossible to update/alter, so i want to delete first to create another with a var as parameter

Final objective : having two calendars, the second one has to disable days before the date choosen in the first calendar by the user. 

COMPLETE CODE

```
<head>
	<title>Calendrier PickMeUp</title>
	
	<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
	
	<link rel="stylesheet" href="http://nazar-pc.github.io/PickMeUp/css/pickmeup.css" type="text/css">
	<link rel="stylesheet" media="screen" type="text/css" href="http://nazar-pc.github.io/PickMeUp/demo/demo.css">
	<script type="text/javascript" src="http://nazar-pc.github.io/PickMeUp/js/pickmeup.js"></script>
	
	<script>
		addEventListener('DOMContentLoaded', function () {
			
			var element = document.getElementById("change");
			
			pickmeup('.dateBegin', {
				min : new Date,
				default_date : false,
				hide_on_select : true, 
				class_name : "beginning", 
				calendars : 3
			});
			

			element.addEventListener('pickmeup-change', function (e) {
				
                                // THE CONDITION WORKS WELL, THE CLASS IS OK, THE CALENDAR IS INITIALIZED, BUT THE DESTROY DOESNT WORK (event problem to catch the DOM element ?)
				if ($( ".ending" ).length) {
					pickmeup('.dateEnd').destroy();
				}
				
				var newDate = e.detail.formatted_date;
				
				pickmeup('.dateEnd', {
					date : newDate,
					min : newDate,
					default_date : false,
					hide_on_select : true,
					class_name : "ending", 
					calendars : 3
				});
				
				pickmeup('.dateEnd').update();
			})
		});
	</script>
</head>


<body>
	<h1>My calendar</h1>
	
	<input  class="dateBegin" id="change" type="text" />
	
	<br></br>
	
	<input class="dateEnd" id="updated" type="text" />
</body>
```

**Comment by nazar-pc** [comment]
Can you put the source on jsfiddle or jsbin like in readme?: https://github.com/nazar-pc/PickMeUp#contribution

**Comment by mystyroi** [comment]
Okay, i've created it here 
https://jsfiddle.net/sL7a2uam/

**Comment by nazar-pc** [comment]
Just released 3.0.8 with fix for this issue.
Let me know if you have any other issues.

**Comment by mystyroi** [comment]
It works great now like I was excepting, thank you !

**Comment by nazar-pc** [comment]
Good to hear, thanks for reporting with working demo!
