### ISSUE TITLE
Вопрос: не инициализируется после раскрытия блока

### ISSUE THREAD

**Issue by sinneren** [nazar-pc/PickMeUp#154]
У меня есть табы. 1 вкладка открыта, на ней дейтпикер и всё хорошо. Вторая вкладка скрыта, на ней тоже есть дейтпикер. Как только мы переключаем табы, вторая вкладка активируется через класс, первая скрывается, то есть в dom уже загружены. Но на ней не работает дейтпикер. Это дефект или я не знаю как работать? Если второе, то как заставить работать его вне зависимости от видимости родителя

**Comment by nazar-pc** [comment]
Нужна демка для воспроизведения проблемы, посмотрите пример здесь: https://github.com/nazar-pc/PickMeUp#contribution

**Comment by sinneren** [comment]
Обошёл через each. Видимо потому что у меня самописный плагин табов.
