### ISSUE TITLE
Tooltips and anchor tags on pmu-selected

### ISSUE THREAD

**Issue by macmasterflash** [nazar-pc/PickMeUp#155]
How can i add tooltips and / or links to a selected day? In the older version i can do something like this, but now this is not working anymore... How can i solve this in the render method?

`$(document).find(".pmu-selected").each(function(){
    if( $(this).is('[class*=myaddedclass]')){
        ...
        $(this).attr('data-toggle','tooltip');
        $(this).attr('data-html','true');
        $(this).attr('data-placement','top');
        $(this).tooltip();
    }
});`

Thanx

**Comment by nazar-pc** [comment]
It should work the same way as far as we consider HTML layout in newer version.
If it doesn't, prepare demo (https://github.com/nazar-pc/PickMeUp#contribution), please. Without demo it is quite difficult to answer your question.
