### ISSUE TITLE
Можно ли выключить определённые даты?

### ISSUE THREAD

**Issue by alfakrai** [nazar-pc/PickMeUp#156]
Здравствуйте. Можно ли отключить определённые даты, сделать их, так сказать, disable?

Документация у вас, если быть честным, так себе... Мало написано, да еще и на буржуйском.

**Comment by nazar-pc** [comment]
Да, в `render` определяете функцию, которая проверяет даты, и для нужных дат возвращаете `{disabled: false}`, в readme даже есть [пример](https://github.com/nazar-pc/PickMeUp#selectingdisabling-dates-with-custom-logic).

**Comment by alfakrai** [comment]
Будьте любезны, приведите пример, в котором отключены вот эти даты: 2017-01-10, 2017-01-15,2017-02-03

**Comment by nazar-pc** [comment]
Я же указал пример, в чём проблема проверить дату на соответствие одной из трех указанных?

**Comment by alfakrai** [comment]
```
var array = ["2017-01-10", "2017-01-15", "2017-02-03"];
        if (date == array) {
            return {disabled : true, class_name : 'date-in-past'};
        }

```
Такое будет работать? 

>  в чём проблема?
Я совсем не знаю js

**Comment by nazar-pc** [comment]
Не будет. Извините, но без знаний JS у вас не получится. А делать работу за вас я тоже не буду.

**Comment by peretc001** [comment]
```
pickmeup('.clndr', {
		flat      : true,
		mode      : 'range',
		calendars : 1,
		format: 'Y-m-d',
		separator: ',',
    	min : new Date(),
    	select_month :false,
        select_year  : false,
        render: function(date) { 
        var disabled_days = [new Date('2017-9-17T21:00:00.000Z'), new Date('2017-9-18T21:00:00.000Z')];
		
        
        for(i = 0; i < disabled_days.length; i++) 
     			if (date.toString() == disabled_days[i].toString()) { 
			return {
                    disabled   : true,
                    class_name : 'disabled'
                } 
			}
		    
        }
    }).clear();
```
