### ISSUE TITLE
Not possible to remove selection from current date

### ISSUE THREAD

**Issue by trasktresk** [nazar-pc/PickMeUp#157]
```
pickmeup('.ev-sidebar_addit-box-calendar', {
        flat: true,
        locale: 'ru',
        format: 'Y-m-d',
        render: function(date) {
            if(date.getDate() === new Date().getDate()) {
                return {selected: false};
            }
        }
    });
```

I tried to remove ".pmu-selected" class by jQuery in callbacks. No effect.

**Comment by nazar-pc** [comment]
Can you describe more precisely what do you want to achieve?
Preferably in 3 parts:
* What are you doing (+ live demo)
* Actual result (wrong)
* Expected result (correct)

This way it would be easier to help you.
