### ISSUE TITLE
Top pisition

### ISSUE THREAD

**Issue by kaifaty** [nazar-pc/PickMeUp#160]
Позиция top при клике.
![image 2](https://cloud.githubusercontent.com/assets/11953142/22290457/5dbfda16-e35d-11e6-82cb-ad12e75d06d2.png)

Позиция top после ресайза окна. 
![image 4](https://cloud.githubusercontent.com/assets/11953142/22290470/6fefd51a-e35d-11e6-994b-142030bd728f.png)

Позиция топ так и задумана?

**Comment by nazar-pc** [comment]
Без демки сложно сказать: https://github.com/nazar-pc/PickMeUp#contribution

**Comment by kaifaty** [comment]
```
#demo.js 
pickmeup('input', {
--		position       : 'right',
++		position       : 'top',
		hide_on_select : true
	});
```
![image 7](https://cloud.githubusercontent.com/assets/11953142/22327249/c4a415a2-e412-11e6-87f6-85556dfcb86b.png)

значение переменной ` root_element.offsetHeight` при первом клике на календаре равно 0.
После ресайза окна браузера значение появляется.

Видится мне это все таки не фича, а баг.

**Comment by nazar-pc** [comment]
Всё равно не понимаю что у вас происходит и что именно у вас не так. Сделайте мне нормальную живую демку на jsfiddle, с подробным описанием что именно не так происходит и как вы ожидали что оно себя поведет.

**Comment by ymfdev** [comment]
Good day! Great plugin, thank you! )
But I have the same problem with top position when I call plugin. After resize get into the right position. 

https://jsfiddle.net/0yzz2jxx/3/

**Comment by nazar-pc** [comment]
Thanks for the demo!
Can you try https://github.com/nazar-pc/PickMeUp/commit/f0e8ece062da57037ff031d3a55874cda0b1499e and confirm that it works properly for you?

**Comment by ymfdev** [comment]
Works correctly. Thank you!

**Comment by nazar-pc** [comment]
Thanks for reporting and testing!
Released as 3.1.3.
