### ISSUE TITLE
Multiple input with same class

### ISSUE THREAD

**Issue by Buzzak** [nazar-pc/PickMeUp#163]
When i have many input with the same class ex: .datepicker only the first element work.
Did i miss something? 
I edited my local PickMeUp.js for this work. Let me know if you want the change.

**Comment by nazar-pc** [comment]
Yes, it only selects first element, this is how `document.querySelector()` works. If you need to apply it to many elements you don't need to edit source, you can just select all necessary elements and initialize PickMeUp on them individually like so:
```javascript
var elements = document.querySelectorAll('.datepicker');
for (var i=0; i < elements.length; ++i) {
    pickmeup(elements[i], {...});
}
```
This is by design.

**Comment by Buzzak** [comment]
Thank you Nazar, but i fixed the source for this work.  That took me 5 minutes lol.

Cause i have different calendar with different init config.

Thank you for taking your time to answer me it's appreciate.


  //Set config PickMeUp pluggin birthdate calendar
    addEventListener('DOMContentLoaded', function () {
      pickmeup('.birthdate',
        {
          first_day: 0,
          default_date: false,
          hide_on_select: true,
          view: 'years',
          mode: 'single',
          min: '1920-01-01',
          max: '2020-01-01',
          date: '1975-01-01',
          format: 'Y-m-d'
        });
    });

    //Set config PickMeUp pluggin datepicker calendar
    addEventListener('DOMContentLoaded', function () {
      pickmeup('.datepicker',
        {
          first_day: 0,
          default_date: false,
          hide_on_select: true,
          view: 'days',
          mode: 'single',
          format: 'Y-m-d'
        });
    });



________________________________
De : Nazar Mokrynskyi <notifications@github.com>
Envoyé : 9 février 2017 18:15
À : nazar-pc/PickMeUp
Cc : Buzzak; Author
Objet : Re: [nazar-pc/PickMeUp] Multiple input with same class (#163)


Yes, it only selects first element, this is how document.querySelector() works. If you need to apply it to many elements you don't need to edit source, you can just select all necessary elements and initialize PickMeUp on them individually like so:

var elements = document.querySelectorAll('.datepicker');
for (var i=0; i < elements.length; ++i) {
    pickmeup(elements[i], {...});
}

This is by design.

**Comment by Buzzak** [comment]
Hello, i have another problem,  maybe you could help me!


When i run the javascript on my local machine pickmeup working #1!


When it published on a windows server 2016 with iis 10 ,the datepicker work the first time perfectly and when i try to select another date while a date is already in the input the datepicker show a date into years 3000+ or a wrong date...


I have no more issue i can't debug the js cause he is minimized.


My initialization


    var elements = document.querySelectorAll('.birthdate');
    for (var i=0; i < elements.length; ++i) {
      pickmeup(elements[i],  {
        first_day: 0,
        default_date: false,
        hide_on_select: true,
        view: 'years',
        mode: 'single',
        min: new Date('1920-01-01'),
        max: new Date('2020-01-01'),
        date: new Date('1975-01-01'),
        format: 'Y-m-d'
      });
    }

    var elements = document.querySelectorAll('.datepicker');
    for (var i = 0; i < elements.length; ++i) {
      pickmeup(elements[i], {
        first_day: 0,
        default_date: false,
        hide_on_select: true,
        view: 'days',
        mode: 'single',
        format: 'Y-m-d'
      });
    }

thank you very much!



________________________________
De : Nazar Mokrynskyi <notifications@github.com>
Envoyé : 9 février 2017 18:15
À : nazar-pc/PickMeUp
Cc : Buzzak; Author
Objet : Re: [nazar-pc/PickMeUp] Multiple input with same class (#163)


Yes, it only selects first element, this is how document.querySelector() works. If you need to apply it to many elements you don't need to edit source, you can just select all necessary elements and initialize PickMeUp on them individually like so:

var elements = document.querySelectorAll('.datepicker');
for (var i=0; i < elements.length; ++i) {
    pickmeup(elements[i], {...});
}

This is by design.
