### ISSUE TITLE
Problem with rendering the good date while published // Edit: Resolved

### ISSUE THREAD

**Issue by Buzzak** [nazar-pc/PickMeUp#168]
I tried with different version of windows server 2016/2012 and different IIS

Calendar initialization :
```
    var elements = document.querySelectorAll('.birthdate');
    for (var i=0; i < elements.length; ++i) {
      pickmeup(elements[i],  {
        first_day: 0,
        default_date: false,
        hide_on_select: true,
        view: 'years',
        mode: 'single',
        min: new Date(1920,1,1),
        max: new Date(2020,1,1),
        date: new Date(1975,1,1),
        format: 'Y-m-d'
      });
    }
```

First time i try to pick a date the calendar is in the good year
![gooddate](https://cloud.githubusercontent.com/assets/17498121/24758681/1132a864-1ab1-11e7-8b2c-4a24673c5594.PNG)

If i try to change the date this is what i get
![wrongdate](https://cloud.githubusercontent.com/assets/17498121/24759277/febb3aaa-1ab2-11e7-9076-f81818a870fe.PNG)

----------------

With the 2e initialization:

```
    var elements = document.querySelectorAll('.datepicker');
    for (var i = 0; i < elements.length; ++i) {
      pickmeup(elements[i], {
        first_day: 0,
        default_date: false,
        hide_on_select: true,
        view: 'days',
        mode: 'single',
        format: 'Y-m-d'
      });
    }
```

First time it's correct

![2egood](https://cloud.githubusercontent.com/assets/17498121/24758927/c3f6f518-1ab1-11e7-9b64-d79bd699ebe1.PNG)

and when i try to change the date,...

![2ewrong](https://cloud.githubusercontent.com/assets/17498121/24758936/cce6d59e-1ab1-11e7-9356-af8575f59715.PNG)

I know on my local machine it work perfectly... I can't debug while it published cause the js is minimized. Plz help ! And thank you

EDIT:

I found the problem, cause i use MVC Bundling minimize for script. The problem is when it minify the pickmeup.js...

I just removed the line in my bundle and added the script in the header like the demo.

Now it work!

**Comment by nazar-pc** [comment]
Glad to know it works for you. If you have any other questions, always create new issue, please.
