### ISSUE TITLE
How can i change the selected Date/Date-Range of a PickeMeUp-Datepicker from the Outside?

### ISSUE THREAD

**Issue by Yunitas** [nazar-pc/PickMeUp#169]
Hello. How can i change the selected Date/Date-Range of a PickeMeUp-Datepicker from the Outside? For Example on a Button Click. Maybe its simple and i just can't see it ... in jQuery Datepicker it is very simple. Thank you very much.

**Comment by nazar-pc** [comment]
Yes, you can use https://github.com/nazar-pc/PickMeUp#set-date for this
