### ISSUE TITLE
position

### ISSUE THREAD

**Issue by iamxor** [nazar-pc/PickMeUp#171]
Used in div with 'display:flex;flex-flow:column;' and position of calendar popup were incorrect.
Modified dom_offset function with thus:

	var x = y = 0;
	if (element.offsetParent) {
		do {
			x += element.offsetLeft;
			y += element.offsetTop;
		} while (element = element.offsetParent);
	}
	return {left : x, top : y};

and voila...

mb usefull 4 smbdy

**Comment by nazar-pc** [comment]
You shouldn't need to modify anything in library itself. Could you share a demo where this happens?

**Comment by iamxor** [comment]
`...
<style>

.checkin-filter-panel {
    display:flex;
    flex-flow:row;
    align-content:center;
    justify-content:flex-start;
    margin:0;
    margin-bottom:10px;
}

.form-label {
    margin:0;
    margin-bottom:10px;    
}

.form-control {
    margin:0;
    margin-bottom:10px;    
}

.checkin-filter-column {
    margin:0;
    margin-right:10px;
    display:flex;
    flex-flow:column;
    align-content:center;
    justify-content:center;
}

.date {
    width:100px;
    text-align:center;    
}
</style>

<div class="checkin-filter-panel">
    <div class="checkin-filter-column">        
        <div>Дата с <input type="text" data-pmu-format="d.m.Y" name="startDate" class="date startDate" /></div>
    </div>
    <div class="checkin-filter-column">        
        <div>по <input type="text" data-pmu-format="d.m.Y" name="endDate" class="date endDate" /></div>
    </div>    
    <div class="checkin-filter-column">
        <div>
            <input type="checkbox"> регистрация запрошена <input type="checkbox"> регистрация выполнена <input type="checkbox"> регистрация отменена<br/>
        </div>
    </div>
    <div class="checkin-filter-column">
        <input type="button" value="Показать" name="checkin-filter-process" class="my-button"/>
    </div>    
</div>
...`
[http://rgho.st/6KsKJPMrW](url)

**Comment by nazar-pc** [comment]
Could you instead modify suggested live demo?: https://jsfiddle.net/qx152r6r/
It is much easier to have a complete example to test with and confirm that issue is fixed afterwards.

**Comment by iamxor** [comment]
mb like thus can't reproduce more clearly cos here in DNN huge bunch of scripts
u can see that positions shifts...
https://jsfiddle.net/qx152r6r/174/

**Comment by nazar-pc** [comment]
In fact, it has nothing to do with `display: flex`, but rather with `body{position: relative}`: https://jsfiddle.net/qx152r6r/175/

Will think about what I can do with it.

**Comment by nazar-pc** [comment]
I've just published 3.1.0 that supports custom function in `position` option, so now it is possible to implement arbitrary positioning in generic way.
