### ISSUE TITLE
question help!

### ISSUE THREAD

**Issue by abhayrajmca** [nazar-pc/PickMeUp#172]
i want to remove current date on onthers selection. why input has current date 2 june

![4 1](https://cloud.githubusercontent.com/assets/25315284/26734029/5275102c-47da-11e7-8687-0db12acc3e2e.png)

**Comment by nazar-pc** [comment]
> i want to remove current date on onthers selection.

Can't quite understand what do you need exactly.

> why input has current date 2 june

Because it was 2nd of June yesterday:)
