### ISSUE TITLE
Получить данные из мультимассива

### ISSUE THREAD

**Issue by SadDeploy** [nazar-pc/PickMeUp#175]
Здравствуйте!
Сделала так https://jsfiddle.net/yyhcncgt/6/
Но событие change не возвращает даты(
Помогите, пожалйуста

**Comment by nazar-pc** [comment]
Более того, оно вообще не вызывается. Актуальная версия вместо этого генерирует DOM события: https://github.com/nazar-pc/PickMeUp#pickmeup-change

**Comment by SadDeploy** [comment]
Методом проб и ошибок, данные получила. Спасибо.
