### ISSUE TITLE
In multiple select can I limit only 2 or 3 day select?

### ISSUE THREAD

**Issue by maisreymom** [nazar-pc/PickMeUp#176]

**Comment by nazar-pc** [comment]
There is no such option out of the box, but there is a possibility to implement this using existing API.

There is a `render` [callback](https://github.com/nazar-pc/PickMeUp#selectingdisabling-dates-with-custom-logic). You can check in this callback if enough dates were selected and simply mark the rest of dates as disabled.

Rendering happens on any change, so this is very flexible way to apply any custom logic like limit of 2 or 3 days as you need.

**Comment by maisreymom** [comment]
I try to use this:
var now = new Date;
pickmeup(element, {
    render : function (date) {
        if (date < now) {
            return {disabled : true, class_name : 'date-in-past'};
        }
        return {};
    } 
})
but it not work.
Excuse me sir, In multiple mode is it possible to click one time but can select multiple date?

**Comment by nazar-pc** [comment]
Yes, it is possible, just look at readme and available options. Also if something doesn't work like you think it should, then make a live demo, please: https://github.com/nazar-pc/PickMeUp#contribution
