### ISSUE TITLE
calendar flat mode-Display only mode

### ISSUE THREAD

**Issue by bandish2189** [nazar-pc/PickMeUp#179]
Hello,

I am using PMU calendar for web portal. 

there are 2 functionality where i am using PMU.

1. select dates when employee will be on leave.
2. Get dates from Employee'd leave table. and display on PMU calender.

ISSUES : 

1. In this 2nd option i am trying to disable any event bound to calneder date,month,year selection.
Because here there is only display functionality on this page. dosent need to select dates from calender. this is only view mode.
Note. i need only highlite provided dates on calender. and disable select or change any event on this calender. How can i achieve this?

**Comment by nazar-pc** [comment]
The first thing that comes to my mind is to attach event listener to relevant elements and just call `e.stopPropagation()` in event handler, so that clicks wouldn't work.
You can also add overlay element with `opacity: 0` that should prevent any clicks on element.

**Comment by bandish2189** [comment]
Thank you for your quick  response.

**Comment by bandish2189** [comment]
Hoe can i disable selection to today and previous dates in calendar?

**Comment by nazar-pc** [comment]
https://github.com/nazar-pc/PickMeUp#selectingdisabling-dates-with-custom-logic

**Comment by bandish2189** [comment]
Thank you for your quick assistance.

**Comment by bandish2189** [comment]
I've recently modified main library file. and added function nameed: dates_in_future() to get selected dates from calender. is there any default method to get such thing?

**Comment by nazar-pc** [comment]
If you need to get dates, https://github.com/nazar-pc/PickMeUp#get-date should be fine, it will return an array if you have multiple dates selected.
