### ISSUE TITLE
 Вывод даты

### ISSUE THREAD

**Issue by peretc001** [nazar-pc/PickMeUp#181]
Добрый день.

Подскажите, пожалуйста, как получить количество выделенных дней?
Я нашел пример скрипта при изменении даты, но почему-то не выводится количество выделенных дней
```
<script>
pickmeup('.clndr', {
		change : function (formatted_date) {
       		$('#return_date').val(addDays('d-m-Y',2));
	    }
	});
</script>
<div id="return_date"></div>
```

Прошу не бить (в js познания 0)
Спасибо

Полный код:
```
$(function () {

var lday = new Date;
	lday.setDate(lday.getDate() - 1);

var l2day = new Date;
	l2day.setDate(l2day.getDate() - 2);
	
var date = new Date;

var tday = new Date;
	tday.setDate(tday.getDate() + 1);
	
	pickmeup('.clndr', {
		flat      : true,
		date      : [
			new Date,
			tday
		],
		mode      : 'range',
		calendars : 1,
		format: 'd-m-Y',
    	separator:';',
    	select_month :false,
        select_year  : false,
        render : function (l2day) {
        if (l2day < lday) {
            return {disabled : true, class_name : 'date-in-past'};
        }
        return {};
    } 
	});
	pickmeup('.clndr').get_date('d-m-Y');
	pickmeup('.clndr', {
		change : function (formatted_date) {
       		$('#return_date').val(addDays(formatted_date,2));
	    }
	});
	
	
});
```

**Comment by nazar-pc** [comment]
У вас код для старой версии библиотеки. Для современной изменение ловить нужно так: https://github.com/nazar-pc/PickMeUp#pickmeup-change
В случае диапазонов и множественного выбора аргумент будет массивом, так что из него можете и получить количество выделенных дней.

**Comment by peretc001** [comment]
Ага, спасибо, так работает

```
$('.clndr').on('pickmeup-change', function (e) {
  		console.log(e.detail.formatted_date); // New date according to current format
    	console.log(e.detail.date);           // New date as Date object
  	});
```

**Comment by peretc001** [comment]
can i ask you one more things?
do you have a function which display a count of selected days?

**Comment by nazar-pc** [comment]
https://github.com/nazar-pc/PickMeUp#get-date

```javascript
pickmeup('.date').get_date().length
```

Read the readme first, please.

**Comment by peretc001** [comment]
i don`t understand, i choose different days, but `count` shows always 2

```
$('.clndr').on('pickmeup-change', function (e) {
var count = pickmeup('.clndr').get_date().length;
console.log(count);
```

**Comment by nazar-pc** [comment]
Yeah, this means you're using `range` mode, in which case you can simply check how many days are there between those 2 dates:
```javascript
var dates_range = pickmeup('.date').get_date();
Math.round((dates_range[1] - dates_range[0]) / 3600 / 24 / 1000)
```

This is are basics of JavaScript.

**Comment by peretc001** [comment]
thank you so much
my basic of JS is - writeLn('Hello World!')  :)

**Comment by peretc001** [comment]
if i disabled some days, how can i check selected days without disabled in range mode
```
var dates_range = pickmeup('.date').get_date();
Math.round((dates_range[1] - dates_range[0] - dates_range[disabled] ) / 3600 / 24 / 1000)
```
and from this
```
$('.clndr').on('pickmeup-change', function (e) {
   console.log(e.detail.formatted_date - disabled); 
});
```

**Comment by peretc001** [comment]
try to select before and after disabled days
https://jsfiddle.net/peretc001/us55fztz/

**Comment by nazar-pc** [comment]
You're deciding in `render` callback which dates are disabled. Which in turn means you are able to exclude those dates from resulting range.
This is not about library itself, but rather about basic JavaScript and dates manipulation.
