### ISSUE TITLE
show/hide question

### ISSUE THREAD

**Issue by dShchet** [nazar-pc/PickMeUp#183]
if the a way to move the show/hide event from an input to another element?
I am trying this https://jsfiddle.net/dShchet/10vcx8b7/ but after click on input, button stopped working

**Comment by nazar-pc** [comment]
There is no way to move event.
I don't understand what exactly you want to achieve.

**Comment by dShchet** [comment]
I want that calendar will show/hide on click on button, but nothing happened on input click

**Comment by nazar-pc** [comment]
A bit hacky, but should work: https://jsfiddle.net/10vcx8b7/1/

**Comment by dShchet** [comment]
Thanks a lot
