### ISSUE TITLE
pickmeup(...) with a selector only affects one element

### ISSUE THREAD

**Issue by kjkrum** [nazar-pc/PickMeUp#185]
This only affects the first element matching the selector:
```js
pickmeup(".fnord", {...});
```
I'm using this workaround to achieve the expected behavior:
```js
$(".fnord").each(function () {
    pickmeup(this, {...});
});
```

**Comment by nazar-pc** [comment]
This is an intended behavior. `pickmeup()` call returns an object that you can use to control the instance.
You can use jQuery or plain JavaScript to apply datepicker to multiple elements.
