### ISSUE TITLE
Не сохраняет выбранную дату (в русской локали)

### ISSUE THREAD

**Issue by liyagan** [nazar-pc/PickMeUp#186]
Если я устанавливаю формат 'A, b d Y', локаль - рус, то не запоминается выбор даты. (и не выделяется стиль)
Запоминает только выбор "Суббота".

https://codepen.io/liya_gan/pen/OORVMB

**Comment by nazar-pc** [comment]
В Firefox Nightly работает корректно, а вот в Chromium Nightly как вы описали.
Странный баг, будем исправлять.

**Comment by liyagan** [comment]
Спасибо за ответ, 
Изменила формат (день недели в конце) и все работает корректно.

**Comment by nazar-pc** [comment]
В последних двух коммитах вроде как исправил, можете проверить работает ли как нужно?
Вот демка: https://codepen.io/anon/pen/MOjwdJ

**Comment by nazar-pc** [comment]
Опубликовал новую версию 3.0.10 с исправлением на NPM, дайте знать если будут ещё какие-то проблемы или вопросы.

**Comment by liyagan** [comment]
Спасибо большое, 
Всё работает.

Еще возник такой вопрос, могу ли я опционально задавать render, из другой функции?

**Comment by nazar-pc** [comment]
Не совсем понятно что имеется ввиду, но задавайте новые вопросы отдельным тикетом, иначе сложно ориентироваться.
