### ISSUE TITLE
Как после инициализации календаря поменять его параметры , опции (в частности render)?

### ISSUE THREAD

**Issue by liyagan** [nazar-pc/PickMeUp#189]
У меня 2 поля формы - список ресторанов и календарь, и в зависимости от ресторана, надо активировать или деактивировать даты?Как после инициализации календаря поменять его опции (в частности render)?

```
render: function(date) {
      if (date.toDateString() === now.toDateString()) {
        console.log(date.toDateString());
        return {
          selected: false
        };
      }
```

**Comment by nazar-pc** [comment]
За вас код писать я не буду, но направление в примере выше верное. Только учтите что у вас время должно быть идентично до секунд (календарь внутри время постоянно сбрасывает в 0, убедитесь что ваш объект `Date` тоже имеет нулевое время для того, чтобы `===` работало).

**Comment by liyagan** [comment]
Меня в данном случае волнует не функция в опции render,
А как изменить эту опцию уже после инициализации pickmeup

**Comment by nazar-pc** [comment]
После инициализации публичных API для изменения опций нет, рекомендуется вызвать метод `destroy()` и инициализировать заново.

Если вы используете `render`, то менять её никакой необходимости быть не должно, ибо функция может брать информацию о том, какие даты изменять извне, оставаясь неизменной.

Если у вас есть какая-то очень специфическая задача (к которой `render` точно не относится), можете попробовать напрямую поредактировать внутреннее состояние (https://github.com/nazar-pc/PickMeUp#other), но в 99.99% это совершенно не нужно. В крайнем случае, я ещё не встречал вопросов, которые нельзя было решить существующими публичными API библиотеки.

**Comment by liyagan** [comment]
Поняла Вас, спасибо!
