### ISSUE TITLE
Add the library to npm

### ISSUE THREAD

**Issue by Beraliv** [nazar-pc/PickMeUp#190]
Could you please add the library to npm not linking it via:

`
{
    "pickmeup": "git://github.com:nazar-pc/pickmeup.git#3.0.11",
}
`

**Comment by nazar-pc** [comment]
It is on NPM for a very long time already (as you can guess from `package.json` in the root of the repo): https://www.npmjs.com/package/pickmeup
I don't know why do you add it as git repository instead.

Latest release for some reason wasn't published, so I've just did that.
