### ISSUE TITLE
Vertical multiple month mode

### ISSUE THREAD

**Issue by gety9** [nazar-pc/PickMeUp#198]
Nazar hi,

Could this datepicker be used to displayed 12 months vertically? 
I would like to achieve something like this > https://puu.sh/zoG71/4cfa7d8c1c.gif

**Comment by nazar-pc** [comment]
Out of the box - no, but I'm pretty sure you can do that with CSS.

**Comment by gety9** [comment]
I would need to run multiple instances for datepicker? One for each month?
And than style with css?

**Comment by nazar-pc** [comment]
Currently in multiple mode several months are placed horizontally, but it is just several `.pmu-instance` elements next to each other. You can force it to wrap each next months as new line stacking them vertically. Then you'll need to hide days of the week (as on gif) and place into some scrollable container. To me it seems pretty doable with single PickMeUp instance.

**Comment by gety9** [comment]
Thank you Nazar, will try your suggestion and reopen if will have issues.

Will close for now.

Thank you for immediate response!
