### ISSUE TITLE
How do I disable multi month view for a single month calendar?

### ISSUE THREAD

**Issue by cretace** [nazar-pc/PickMeUp#200]
Question
I have a single month view - if I click the prev/next arrows fast I get the display of 'many month names' or 'many years'.
Can I disable that so it's strictly month by month?
I can't see it in the options list.
Thanks for great plug in!

**Comment by nazar-pc** [comment]
I don't quite understand what you mean by `I get the display of 'many month names' or 'many years'`. Are you sure you're clicking strictly on arrows and not on the area between them?

**Comment by cretace** [comment]
Thanks Nazar .
It's not me - it's my users ! 
I guess they are clicking in the wrong place but they don't like the feature as they only ever need to go a a few months forward.
Can I disable it?

**Comment by nazar-pc** [comment]
I think what you want is to set both `select_month` and `select_year` to `false`, then clicking between arrows will have no effect.

**Comment by cretace** [comment]
Ah, that's it thanks
