### ISSUE TITLE
How can i add ok and cancel button

### ISSUE THREAD

**Issue by niteshkumar-singh** [nazar-pc/PickMeUp#201]
How can i manage close and set date on button and append on this

**Comment by ThakurNiteshkumarSingh** [comment]
Sorry Sir can you give some example of that in jsfiddle or codepen

**Comment by nazar-pc** [comment]
Sorry, don't have time for that.
Basically look at readme, there is information how to get/set dates manually, you can use that for your buttons.

**Comment by niteshkumar-singh** [comment]
OK, i understand but ia have no problem with set/get. i am facing how to add ok and cacel button append on datepicker can you help me please.

**Comment by nazar-pc** [comment]
If you don't have issues with get/set then library is working as expected. So what you're asking is to do your work and I have no time for that currently.
