### ISSUE TITLE
how to apply value in two input for range datepicker

### ISSUE THREAD

**Issue by niteshkumar-singh** [nazar-pc/PickMeUp#203]
how to apply value in two input for range date picker

**Comment by nazar-pc** [comment]
Range mode supports getting and setting dates as an array of 2 items, so you can just get values from those 2 fields and call `.set_date([date_from, date_to])`.

**Comment by niteshkumar-singh** [comment]
It show show error : Uncaught ReferenceError: date_from is not defined

**Comment by nazar-pc** [comment]
Of course, you have to create variable with that name and put contents of corresponding input into it.
