### ISSUE TITLE
How to clear input value after selecting date

### ISSUE THREAD

**Issue by niteshkumar-singh** [nazar-pc/PickMeUp#204]
How to clear input value after selecting date

**Comment by nazar-pc** [comment]
Well, just listen to `change` event and whenever change happens clear input. However, I don't really understand why do you even need an input in that case.

**Comment by niteshkumar-singh** [comment]
Dear Sir, i need clear input if i click on cancel or close button and set if i click on ok button

**Comment by nazar-pc** [comment]
`element.value =''` with plain JavaScript should be fine. Similarly you can set value with date whe user clicks OK. These are very basics of JavaScript.

**Comment by niteshkumar-singh** [comment]
Thanks
