### ISSUE TITLE
invalid check "date instanceof Number"

### ISSUE THREAD

**Issue by nikedev** [nazar-pc/PickMeUp#213]
https://github.com/nazar-pc/PickMeUp/blob/f886f03eaad532f5ba5ff6b7706eff5fd341bf40/js/pickmeup.js#L550

I think that the check is not working correctly.
For example, if I pass time in milliseconds in the max parameter, then the check will not work.
Probably worth checking out in the following way.
`typeof date === 'number'`

**Comment by nazar-pc** [comment]
I think you are right, PR is definitely welcomed

**Comment by nazar-pc** [comment]
Fixed in 3.2.1
