### ISSUE TITLE
Add composer.json file

### ISSUE THREAD

**Issue by multiwebinc** [nazar-pc/PickMeUp#221]
I can't include this as a dependency using composer.json because this repository doesn't have a composer.json file

> No valid composer.json was found in any branch or tag of https://github.com/nazar-pc/PickMeUp.git, could not load a package from it.

**Comment by nazar-pc** [comment]
This is a frontend package, so you should use NPM and `package.json` to install it or trying something like https://github.com/fxpio/composer-asset-plugin
