### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by rudireg** [nazar-pc/PickMeUp#228]
Hi. Is there any possibility to add one footer if I have 2 calendars.

**Comment by nazar-pc** [comment]
Not a common one, but you can always place calendars into a different container.
Another (and bad, but working) way would be to add what you need to the end of `instance_template` and just hide extra copies with a bit of CSS.

**Comment by rudireg** [comment]
Thanks.
A root pickmeup element can be accessed as `element.__pickmeup.element`
and this will help me.
