### ISSUE TITLE
For Two textboxes it is coming(i.e.., for the first and the fourth) and i want only for fourth one to be a date picker

### ISSUE THREAD

**Issue by AkhilReddy30** [nazar-pc/PickMeUp#230]
Date picker is coming for first textbox and also fourth textbox i want it only for the fourth text .First text should be served for another purpose

**Comment by nazar-pc** [comment]
Sorry, I do not understand the question. Can you elaborate?

**Comment by AkhilReddy30** [comment]
Means i want to keep date picker inside a form and in that form there are  7 input  fields but date picker is coming for first input field only(but i don't need it there) when i add class date for fourth input  field(where i need date picker) then it is showing  picker but selection is not possible for fourth input field

**Comment by nazar-pc** [comment]
Still not sure what is going on wrong... you can apply it to any field or even use without input field and read/write text field in your code to trigger datepicker show/hide.

**Comment by AkhilReddy30** [comment]
I fixed it
