### ISSUE TITLE
Добавить параметр для скрытия дат из соседних месяцев

### ISSUE THREAD

**Issue by Creaternal** [nazar-pc/PickMeUp#34]
Сильно мешает отсутствие такой настройки, когда выводится больше одного календаря в режиме диапазона. Но и других случаях может быть полезно.

![1409903982566](https://cloud.githubusercontent.com/assets/2980701/4161811/aca1a880-34d2-11e4-8602-a262b758ddc2.jpg)

**Comment by error404as** [comment]
Считаю, что проблему надо всё же решить. Одно дело, когда часть недели попадает в другой месяц - а другое дело, когда целые неделю другого месяца показаны.
visibility: hidden в данном случае только ухудшает картину: http://i.imgur.com/CUiIYpp.png (см Февраль 2015 с начальным днем 0).

**Comment by nazar-pc** [comment]
@error404as, а с этим ничего не поделать, это частный редкий случай, когда месяц начинается в воскресенье и в нём только 28 дней, весьма редкое событие, согласитесь. Чтобы выглядело более приятно можно не прятать дни, а просто делать их сильно прозрачными.
