### ISSUE TITLE
Dynamically change locale

### ISSUE THREAD

**Issue by faiwer** [nazar-pc/PickMeUp#44]
How I can dynamically reload locale? Only .destroy + .pickmeup() again?

В приложении есть необходимость смены языка на лету. В текущей кодовой базе есть возможность перестройки HTML по требованию? Судя по:
```
if ($this.data('pickmeup-options')) {
  return;
}
```
нету :) или я плохо искал? воспользовался убиением и последующим воскрешением с прежними параметрами. Но это не очень производительно.

**Comment by nazar-pc** [comment]
Master branch contains support for multiple locales.
Since some parts of PickMeUp are generated during initialization for efficiency, you'll need to destroy/create instance. But this is not likely to happen often, so I'm closing this as implemented.
