### ISSUE TITLE
Unable to change start date when scrolling to a  previous month

### ISSUE THREAD

**Issue by akhilclarion** [nazar-pc/PickMeUp#48]
Unable to change start date when scrolling to a

previous month, i.e. Dec. 12 to Jan. 11. Month selector remains frozen on 

Dec. and will not go back to January. Same for year selector, it would not 

choose 2015.

**Comment by nazar-pc** [comment]
Can you make some demo with exact steps to reproduce?

**Comment by akhilclarion** [comment]
hi Nazar,

You fixed the bug, thank you so much !!!!!
