### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by gleam-ru** [nazar-pc/PickMeUp#52]
Спасибо за модуль, пригодился.

Только сначала не увидел всплывающий календарь...
решение оказалось таким:
http://joxi.ru/8AnBg5Xf0VyRAO

Возможно, есть смысл добавить его в исходники?

**Comment by nazar-pc** [comment]
Это зависит от проекта. Одному нужно `z-index: 1`, другому `100`, а кому-то `1000`.
Это сильно зависит от того, в каком контексте вы его используете.

**Comment by gleam-ru** [comment]
Не, я это понимаю, 1000 взял для примера :)
Просто не могу представить ситуацию, когда календарь должен оказаться под другим элементом, вот и предложил добавить хоть какой-то z-index по-умолчанию, чтобы не казалось, будто модуль не работает.

**Comment by nazar-pc** [comment]
На обычной странице `z-index` не нужен, а в любом всплывающем окне уже индивидуальная ситуация и нужно будет всё равно менять. А если каледарь будет на странице, а потом при открытии всплывающего окна окажется поверх него - тоже будет достаточно странно. Слишком индивидуальный параметр.

**Comment by gleam-ru** [comment]
Это было всего лишь предложение, даже, скорее, отзыв пользователя. Прислушиваться к нему или нет - ваш выбор.
В любом случае - спасибо за модуль!
