### ISSUE TITLE
Method 'set_date' does not update input value.

### ISSUE THREAD

**Issue by basgren** [nazar-pc/PickMeUp#53]
I use input field with single date select, and when I use 'set_date' method to set new date, the input value and date picker representation remains the same, while 'get_date' returns the date I have just set.

I found a workaround - to set input value directly and then call 'update' method, but it's a bit inconvenient, as I have to format date before setting input value, while I'd prefer to use native js Date object.

Thank you.

**Comment by nazar-pc** [comment]
Fixed in c797889
