### ISSUE TITLE
Disabling paging when selecting a date

### ISSUE THREAD

**Issue by Nadoedalo** [nazar-pc/PickMeUp#54]
How to disable changing of the current month when using the 3 calendars + range demo?
It happens when you click on left or right month and sometimes is kind of unexpected.

Also can I have my own types of selection? Like quarter picker?

**Comment by nazar-pc** [comment]
First already reported as #41.
Can you explain more detail about types of selection?

**Comment by Nadoedalo** [comment]
It's the same as month selection, but Jan-Feb-Mar replaced with I, II, III, IV and custom callback function when clicked. On those one I want to select 3 month at once

**Comment by nazar-pc** [comment]
Sorry, but I do not think it is common enough to include into plugin, very edge case.
First part will be fixed with #41, follow it to know when.
