### ISSUE TITLE
Month range select from first to last date in selected period

### ISSUE THREAD

**Issue by Nadoedalo** [nazar-pc/PickMeUp#55]
Any thoughts about how to enable first-day to last day month selection?
Now I have 01.01.2015-01.02.2015, want to have 01.01.2015-10.02.2015(i.e the last day of current month)

**Comment by nazar-pc** [comment]
Wait, but 10.02.2015 is not last date of February, it was current day at the moment of writing.
Can you clarify what you mean?

**Comment by Nadoedalo** [comment]
It's the last day that can be selected to form a report, I place current date as max date.

Остальное-то всё понятно или тоже разъяснить? Просто писать на русском нехорошо т.к эти вопросы-ответы не будут потом гуглится.

**Comment by nazar-pc** [comment]
Well, this is very easy to achieve with `change` event:
```js
...
        change  : function () {
            $(this).pickmeup('set_date', [$(this).pickmeup('get_date')[0], new Date]);
        }
...
```
Demo: http://jsfiddle.net/z4fmvuzb/32/

**Comment by Nadoedalo** [comment]
Seems laggy and not working correctly... Looks like recursive change event.
http://jsfiddle.net/jz0xq9Lf/8/
The second date has always 1st of current month, want - max date(i.e 31,30,29/28) or the max from the current month(for now it is 11)

**Comment by nazar-pc** [comment]
> The second date has always 1st of current month

Wrong, first day of second selected month.

> want - max date(i.e 31,30,29/28) or the current day from the current month(for now it is 11)

Will this help?:
```js
date.addMonths(1);
date.addDays(-1);
if (date > max_date) {
  date = max_date;
}
```
Use this in callback before output, or patch internal `options.date` before calling `get_date` method (I personally do not recommend this to avoid any further issues).
Also `$('.range').data('pickmeup-options').format` in demo makes no sense, because current format assumed by default.

**Comment by Nadoedalo** [comment]
> Also $('.range').data('pickmeup-options').format in demo makes no sense, because current format assumed by default.
Wrong, data will be different from formated because by default it returns the original date object
http://jsfiddle.net/jz0xq9Lf/11/
>Wrong, first day of second selected month.
Yeah, the second date will be always 1st, so when you select only one month you will select 01-01-2015 to 01-01-2015, not 01-01-2015 to 31-01-2015 as it is expected.

I'm not calling "get_date"(exept of after initialize, and it is OK to have only one date of today), I'm changing inputs by change callback.

**Comment by nazar-pc** [comment]
> Wrong, data will be different from formated because by default it returns the original date object
http://jsfiddle.net/jz0xq9Lf/11/

Yeah, sorry, you have to put `true` here to use default format
> I'm not calling "get_date"(exept of after initialize, and it is OK to have only one date of today), I'm changing inputs by change callback.

So, you can modify second date in `change` event, right?

**Comment by Nadoedalo** [comment]
done with changing the callback for periods - now it modyfies the second date, but isn't formatting as the widget(so it is hardcoded)
```javascript
 changeDatePeriod : function(dates, datesObj){ //fixme должен быть задан формат в зависимости от того который в календаре указан
            var sdo = datesObj[1],
                sd;
            sdo.addMonths(1);
            sdo.addDays(-1);
            sd = sdo.getFullYear()+'-'+('00'+(sdo.getMonth()+1)).slice(-2)+'-'+('00'+(sdo.getDate())).slice(-2);
            dates[1] = sd;
            this.changeDate(dates);
        }
```

**Comment by nazar-pc** [comment]
Is your problem fixed now and we can close this issue?

In fact, I'm not currently actively using this plugin. It inherited most of structure and inner code from original datepicker by Stefan Petre, and it can be much better (events be like normal DOM events with multiple callbacks if needed, better inner structure, probably, more optima, etc.), but I do not have much time for that right now.
