### ISSUE TITLE
Баг при выборе периода

### ISSUE THREAD

**Issue by sovetkin-am** [nazar-pc/PickMeUp#56]
Собственно если hide_on_select: true + mode: 'range', то после второго клика по input сбрасывается в инпуте конечная дата на начальную

**Comment by nazar-pc** [comment]
Demo?

**Comment by sovetkin-am** [comment]
http://jsfiddle.net/2f730tqv/ - вот тут песочница, если повторно начать выбирать промежуток, то в инпуте сбрасывается конечная дата на начальную

**Comment by nazar-pc** [comment]
Should be fixed in 041c295
