### ISSUE TITLE
Disabled dates + bootstrap

### ISSUE THREAD

**Issue by CathomeDailyMusic** [nazar-pc/PickMeUp#59]
I'm using bootstrap integrated version.
My issue is, I have noticed that disabled dates don't change their appearance compared to normal dates. 
So I have changed disabled variable in jquery.pickmeup.twitter-bootstrap.min.js

![screenshot from 2015-03-03 21 15 55](https://cloud.githubusercontent.com/assets/11299662/6469304/5a7dc668-c1ec-11e4-9ed4-59ac0a409a0a.jpg)

because I haven't found "uk-button" class in bootstrap css files. 
Please tell if I'm misunderstanding something or there is a problem.

**Comment by nazar-pc** [comment]
Sorry, that was a typo from my side, does `text-muted` works fine for you?
I'll apply it upstream.

**Comment by CathomeDailyMusic** [comment]
Yes, greyed-out dates seem fine to me.

**Comment by CathomeDailyMusic** [comment]
Yes, greyed-out dates seem fine to me. Thank you.

**Comment by nazar-pc** [comment]
Thank you, included in fresh [2.6.4 release](https://github.com/nazar-pc/PickMeUp/releases/tag/2.6.4)
