### ISSUE TITLE
Показ в ie8

### ISSUE THREAD

**Issue by mekela** [nazar-pc/PickMeUp#61]
доброго дня.
підкажіть, будь ласка, як виводити календарний блок в іе8. На даний момент він просто відсутній.

**Comment by nazar-pc** [comment]
На сторінці плагіну заявлена підтримка IE10+, старіші версії не підтримувались і не будуть, чого і вам рекомендую.

**Comment by mekela** [comment]
стилі я налаштую, мені потрібно щоб виводився календар так само як і в іе9.
Дякую

**Comment by nazar-pc** [comment]
Тоді дивитись консоль браузера чого йому не вистачає, може `Function.prototype.bind`, може ще чогось, треба буде поліфіли підключати.
