### ISSUE TITLE
Закрытие открытого календаря по клику на то же поле

### ISSUE THREAD

**Issue by error404as** [nazar-pc/PickMeUp#62]
Сейчас календарь не закрывается, если кликнуть повторно на поле, которое его открыло. Приходится писать кастыли через before_show и setTimeout.

**Comment by nazar-pc** [comment]
Не вижу костылей и смысла добавлять это в ядро плагина.
Вот так можно это реализовать: https://jsfiddle.net/z4fmvuzb/78/
```js
$('input').pickmeup({
	position		: 'right',
	hide_on_select	: true,
    show            : function () {
        if (this.pickmeup.is(':visible')) {
            $(this).pickmeup('hide');
            return false;
        }
    }
});
```
Достаточно просто и лаконично
