### ISSUE TITLE
Input not updating with selected date

### ISSUE THREAD

**Issue by bl4ckdu5t** [nazar-pc/PickMeUp#65]
I'm using this in a rails application and initializing it on all date inputs with:
```javascript
$('[type=date]').pickmeup();
```
but when the date drops down and I select a date, it fails to update the input. It's like my clicks are just ignored

**Comment by nazar-pc** [comment]
Does [demo](https://nazar-pc.github.io/PickMeUp/) works for you?
If so, I need some demo which reproduces issue. Look at the end of readme, there is sample JSFiddle page, modify it to reproduce issue.

**Comment by bl4ckdu5t** [comment]
Thanks for your feedback. The demo works and it eventually worked on my application when I used a class selector on text field input like:
```javascript
$('.date').pickmeup()
```
on
```
<input type="text" class="date">
````
I'd initially thought it'll override chrome's default date function on date field inputs but it didn't.
