### ISSUE TITLE
Добавить два диапазона в range.

### ISSUE THREAD

**Issue by PaulSmiths** [nazar-pc/PickMeUp#66]
Здравствуйте, возможно ли добавить два и более диапазона в моде range?
date : [
      '05/04/2015',
      '15/04/2015'
 ]

**Comment by nazar-pc** [comment]
Нет, range на то и range, что поддерживает два параметра: от и до.

Возможно, вам подойдет multiple режим, там можно выбирать произвольное количество любых дней, используя события можно обеспечить то, что вам нужно, но для этого нужно написать некоторое количество кода, которое зависит от вашей конкретной ситуации.

**Comment by PaulSmiths** [comment]
Ок, благодарю!
