### ISSUE TITLE
No default_date

### ISSUE THREAD

**Issue by amarsyla** [nazar-pc/PickMeUp#67]
There should be a possibility to not set a default_date. When you click the input for the first time, it should stay empty until a date is selected. The best way for this would be to add support for a 'false' bool value to the default_date option.

**Comment by nazar-pc** [comment]
Please can you make demo and show exactly what is going wrong on your opinion?

**Comment by amarsyla** [comment]
This is actually a feature request, not a bug. I want to set no default_date. Which means, that after I initialize the plugin on an input, and when I focus on the input, when the calendar shows I don't want today's date to be selected. I want to select a date on my own.

**Comment by nazar-pc** [comment]
Actually, this option was added, as I remember, just for that, that is why I was asking for demo.

**Comment by amarsyla** [comment]
I think you're not understanding me. Yes, default_date is added, but I want NOT to select a default_date. I want it to be empty. I want the input to be filled with a date only when I select one, and not immediately after the focus on the input.

**Comment by nazar-pc** [comment]
Now I understand what you mean. I'll add it to TODO list, feel free to send pull request if you'll make it faster.
I can't promise it will be done very soon.

**Comment by amarsyla** [comment]
I am already doing it, I will send for review in a few minutes...

**Comment by amarsyla** [comment]
I did a pull request, please compare and test if everything works well.

**Comment by amarsyla** [comment]
Have you had some time to review the pull request?

**Comment by nazar-pc** [comment]
Not yet, I hope tomorrow.
