### ISSUE TITLE
Выбор сегодняшней даты / Несколько выбранных дат

### ISSUE THREAD

**Issue by evgenyzenka** [nazar-pc/PickMeUp#74]
Здравствуйте. Столкнулся с такой проблемой: когда календарь инициализируется - сегодняшняя дата по умолчанию выбрана, не вижу как это изменить

И еще, когда в опции date указано несколько дат, которые должны быть выбраны при загрузке календарь показывается не на текущем месяце, а на месяце, который первый в массиве в date
к примеру, если указано date: ['01.01.1970','12.05.2015'] - календарь будет открыт на январе 1970 года :)

**Comment by nazar-pc** [comment]
> сегодняшняя дата по умолчанию выбрана, не вижу как это изменить

Параметры `date` и `default_date`

> И еще, когда в опции date указано несколько дат, которые должны быть выбраны при загрузке календарь показывается не на текущем месяце, а на месяце, который первый в массиве в date

Логично же, если вы захотите изменить дату - выбранную более логично показывать, чем сегодняшнюю.

**Comment by evgenyzenka** [comment]
а если в каждом месяце их по несколько штук? Вот, например, для магазина указываются нерабочие дни:
в этом месяце, потом в следующем, через год - не все же время показывать самую первую дату

**Comment by nazar-pc** [comment]
А дайте пример на jsfiddle или подобном, посмотрю.

**Comment by evgenyzenka** [comment]
http://jsfiddle.net/jf304wqm/

**Comment by nazar-pc** [comment]
Вы не указали `format`, так что оно в любом случае не работало бы, но да, берется первая дата вместо последней.
Буду рад принять pull request)

**Comment by evgenyzenka** [comment]
знать бы еще как его создать :)
а почему-то не работает у меня default_date. Я так понимаю, если он false - то сегодняшний день не должен быть выбран?

**Comment by nazar-pc** [comment]
> знать бы еще как его создать :)

Учиться никогда не поздно (на самом деле форкаете, меняете, потом появится кнопочка предложить изменения), просто я не знаю как скоро у меня будет время заняться этим вопросом.

> а почему-то не работает у меня default_date. Я так понимаю, если он false - то сегодняшний день не должен быть выбран?

Верно, для текстового поля с `mode: 'single'`. Эту фичу добавил другой пользователь вроде вас, для `multiple` и `range`, равно как и для `flat: true` это не реализовано.

Нужно будет как-то выделить время и позакрывать таски, но пока имеем что имеем.

P.S. Настоятельно рекомендую разные вопросы задавать отдельно! Это упрощает анализ и контроль над исправлением.

**Comment by Muskos** [comment]
`date_default` for `flat: true`
You can reset date after init:
`$('#calendar').pickmeup('set_date', false);`

**Comment by nazar-pc** [comment]
First part should be fixed in 9ba885e
Second part should be fixed in 42fb674
