### ISSUE TITLE
Feature Request: Responsive calendars or font-size

### ISSUE THREAD

**Issue by EHLOVader** [nazar-pc/PickMeUp#76]
Ability to define a responsive layout, like number of calendars to fill the width of the space. `font-size` to grow and shrink given extra space or breakpoints.

Some of this could be handled with just some simple css but the calendars would take a small amount of logic somewhere.

**Comment by nazar-pc** [comment]
You can scale calendar with `font-size`, but it is not clear what you want to achieve here, what breakpoints do you mean?

**Comment by EHLOVader** [comment]
I know about the `font-size `. That was mentioned. I was taking about using
media query breakpoints. The breakpoints you often find in responsive web
design.   Specifically being able to set the number of calendars and then
the funny size to fill the space available. The goal is to fill the space
or perhaps more immediately useful prevent unwanted wrapping of the
available space becomes to small.

Font size is nice but it is too fine of control for simply filling a column
in a RWD grid whose width is defined by a percent.

The effect I am after is more like this than explicitly setting a size.
http://www.zachleat.com/web/bigtext-makes-text-big/

**Comment by nazar-pc** [comment]
Well, responsive layout is usually quite custom thing, not sure we can easily fit it to be useful out of the box. Currently you can check page width at initialization and reinitialize when page size changes, also you can apply any css rules, but to support this out of the box might be too big overcomplication and do not worth it.

**Comment by EHLOVader** [comment]
Here is a specific case. I am using bootstrap and their grid for breakpoints. But as you can see at many screen sizes the appearance of the calendar could use some work.

The really large screen sizes leave extra unused space and font-size could be increased.

![huge screen](https://cloud.githubusercontent.com/assets/701725/7775919/1f76733a-0085-11e5-880d-8b2040a967f2.png)
)

Slightly smaller is probably the best that it looks.
![big screen](https://cloud.githubusercontent.com/assets/701725/7775889/f00db2d4-0084-11e5-8665-1032a4b097a4.png)

This is where it starts to break, calendars start wrapping, and font size could go smaller but it could be harder to use. So I would probably go to 1 calendar instead of 2.
![small screen](https://cloud.githubusercontent.com/assets/701725/7775910/129c835c-0085-11e5-91a2-5becbad8f868.png)

Then smaller yet. And all of a sudden at this new breakpoint I have room for 3 calendars. That would be nice for users to be able to choose. Or perhaps just a larger fonts.
![smaller screen](https://cloud.githubusercontent.com/assets/701725/7775944/413e5d70-0085-11e5-83e9-a891b7f4f1f5.png)

Then the smallest screen and it wraps again creating a strange layout for 2 calendars.
![smallest](https://cloud.githubusercontent.com/assets/701725/7775959/6558063e-0085-11e5-8733-0235bd2fa1ef.png)

I don't think that specific breakpoints should be in the core. But you have already done a lot to make the font size scaling possible and clean it would be nice to see something for handling calendars on resize as well.

**Comment by nazar-pc** [comment]
In fact, scaling is completely in CSS, there is nothing connected to it in JS. While implementing such feature will require to listen for window size change event and extend configuration further to implement what you need.
Instead, you can listen for that yourself, and if some breakpoint crossed - destroy it and initialize again with different settings. I'm afraid including all this will make config messy.

**Comment by EHLOVader** [comment]
Forget I ever said anything about scaling please. I know that you can do it in CSS but I want to do it sometimes and sometimes not based on a dynamic number of calendars.

Calendar count. I would like this to be about the number of calendars to fit a given size of the screen. 

When the screen gets too small for 2
![image](https://cloud.githubusercontent.com/assets/701725/7777082/f5e2d50a-008d-11e5-92db-dac9a59ca756.png)
it should go to 1

when the screen gets large enough for more..
it should go to 3
![image](https://cloud.githubusercontent.com/assets/701725/7777092/04a6fa44-008e-11e5-8760-47c219c84a52.png)


This is a feature which would require some configuration. Max number of calendars, Min number of calendars. And probably the fit or not fit setting.

**Comment by EHLOVader** [comment]
May look into the destroy options, but that seems like a lot of work for something like this. 

Thanks.

**Comment by nazar-pc** [comment]
I believe such features might be much easier to implement if PickMeUp have better internal structure which is not the case yet.
Also, you can create wrapper for PickMeUp like TB and UIkit integrations does to automate this and even support custom configuration options.

**Comment by EHLOVader** [comment]
Thanks, I hadn't thought of that, but it will help a bit.

**Comment by multiwebinc** [comment]
This would actually be very easy to accomplish with CSS alone if we could just move the previous and next buttons to be siblings of `.pmu-instance` instead of children since they always need to be available even if a calendar isn't.

Here is an example with 4 calendars (note, I'm just guessing the break points):

```
@media (max-width: 600px) {
  .pmu-instance + .pmu-instance {
    display: none;
  }
}
@media (max-width: 800px) {
  .pmu-instance + .pmu-instance + .pmu-instance {
    display: none;
  }
}
@media (max-width: 1000px) {
  .pmu-instance + .pmu-instance + .pmu-instance + .pmu-instance {
    display: none;
  }
}

```

**Comment by multiwebinc** [comment]
@nazar-pc Can you be a bit more specific? I don't see anything in the documentation about custom buttons. Taking a quick look at the code, I'm assuming setting `instance_template` and `instance_content_template`?

**Comment by nazar-pc** [comment]
I mean there are methods you can call to initiate switching months back and forth. Hence you can wrap datepicker with another element and create whatever shell and UI you like.
Making templates customizable though might be a pretty good idea.

**Comment by multiwebinc** [comment]
Ok, I thought about how to do this a bit more, and you can actually *almost* accomplish this with pure CSS:

e.g. for 2 calendars:
```
@media (max-width: 550px) {
  .pmu-instance + .pmu-instance {
    width: 0 !important;
    height: 0 !important;
    padding: 0 !important;
    overflow: hidden;
  }

  .pmu-next {
    position: absolute;
    top: 8px;
    right: 7px;
  }

  .pmu-month {
    margin-right: 50px !important;
  }
}
```

However the problem is that when you choose 2 calendars in the JS, but the screen width is only wide enough to display one, and a date in a future month is selected, then when you open the calendar it will default to the month before the selected month because it assumes the other calendar is also being displayed.

If you could modify the JS code to simply add a class to `.pmu-instance` (such as `pmu-has-selection`) for any months that currently have dates selected somewhere in them, then you could use this technique to hide all except for the first element matching `.pmu-instance.pmu-has-selection`.
