### ISSUE TITLE
Можно ли с опциями min и max сделать подсвечивание текущей даты не в заданном диапозоне?

### ISSUE THREAD

**Issue by nmwebis** [nazar-pc/PickMeUp#78]
Нужно сделать подсвечивание текущей даты, например, 26.05.15 или 14.09.15, с опциями min: 10.07.15 и max: 03.08.15. Хочется без костылей, само собой.
Основная проблема в том, что при задании опций min и max мы не можем перелистывать месяца и года, если они находятся не в выбранном диапазоне.

**Comment by nazar-pc** [comment]
Ничего не понял. Можно конкретно:
1) Делаю А
2) Получается Б
3) Ожидалось С
или что-то в этом роде?

**Comment by nmwebis** [comment]
$('.date').pickmeup({
    min: '10.07.15',
    max: '03.08.15'
});

Хочу, чтоб в календаре цветом отметилась текущая дата: 26.05.15, а при выборе значения из диапазона '10.07.15' - '03.08.15' этот селект не снимался.

**Comment by nazar-pc** [comment]
Ну так стилизируйте `.pmu-today`

**Comment by nmwebis** [comment]
Календарь не дает мне возможности перемотать на май, потому что минимальная дата 10 июля. Я про это и писал в первом посте во втором абзаце. При инициализации мне отображается июль и никак я не смогу увидеть 26 мая.

**Comment by nazar-pc** [comment]
Так было задумано, вы можете использовать событие `render` вместо `min`/`max` и вручную отключать нужные даты. Тогда их нельзя будет выбрать, но переключение месяцев будет работать.
