### ISSUE TITLE
Возможность отключения выбора некоторых дат.

### ISSUE THREAD

**Issue by borovik96** [nazar-pc/PickMeUp#80]
Будет ли возможность отключения некоторых дат? Например так
![image](https://cloud.githubusercontent.com/assets/9018702/8024508/e5f49788-0d3e-11e5-9af5-5b4286c14a08.png)

**Comment by nazar-pc** [comment]
Есть событие `render`, с его помощью можно реализовать необходимую вам функциональность:
https://github.com/nazar-pc/PickMeUp#object-render-date
