### ISSUE TITLE
Добавление двух типов дат.  

### ISSUE THREAD

**Issue by Baster** [nazar-pc/PickMeUp#81]
Здравствуйте, использую multiple режим для создания более одного диапазона. Хотелось бы им дать ещё разные классы, чтобы управлять цветом, это возможно?

**Comment by nazar-pc** [comment]
Классы можно назначать с помощью события `render`

**Comment by Baster** [comment]
Извините, сколько пытаюсь, но не могу разобраться. Пишу так:
$('.employment').pickmeup('set_date', date);
Где date это массив дат такого типа - 0: 1429041600000 1: 1427832000000 и т.д, все работает, но не могу понять как вызывать событие render и class_name, пробовал по примерам, но он просто перестает работать.

**Comment by nazar-pc** [comment]
Событие `render` само вызывается на при рендеринге каждого отдельного дня в календаре.
Проверяете что за день, если нужно - добавляете определённый класс.
