### ISSUE TITLE
Great component, but does not properly work with IE

### ISSUE THREAD

**Issue by neilyoung** [nazar-pc/PickMeUp#82]

**Comment by nazar-pc** [comment]
Although I do not care that much whether it works in IE this message is completely useless until you provide some more details (in this case I'll reopen issue).

**Comment by neilyoung** [comment]
So if you don't care it would have been much more useless to provide details.

**Comment by nazar-pc** [comment]
Any chances to know version of IE? OS?

**Comment by neilyoung** [comment]
:) So now we are discussing. That's why I didn't want to jump in directly...

OK. This is an IE 11 here running on Windows 8. Attached two screenshots, one made with Chrom, the other with IE

![chrome](https://cloud.githubusercontent.com/assets/731020/8131730/95d6c26c-111c-11e5-9603-960e58db1d30.jpg)
![ie11](https://cloud.githubusercontent.com/assets/731020/8131731/99797f2c-111c-11e5-9afa-f586908b1454.jpg)

**Comment by nazar-pc** [comment]
Since you have square borders - I guess you are running IE in compatibility mode, and since IE9- are not supported layout will break.
Can you confirm this?

**Comment by neilyoung** [comment]
Pretty good catch. Indeed, parts of my customers are still running on IE8. For some other reasons it was necessary to add the meta tag IE-EmulateIE8 to my site. Totally forgot about this.

Confirm, it works in IE11

Thanks

**Comment by nazar-pc** [comment]
For IE8 you can tweak CSS to make it working (since it doesn't know what `display: flex` means), but no promises since it is not officially supported.
