### ISSUE TITLE
Input and range calendar

### ISSUE THREAD

**Issue by jmoron82** [nazar-pc/PickMeUp#83]
Hi Nazar,
 
I got a range calendar working well, I need to send the selected values to a input , how can I do that?

For now i have this:

html:
<input type="text" value="">
<div class="range"></div>

js:

$(function () {
	$('input').val(
	    $('.range').pickmeup({
			flat	: true,
			mode	: 'range',
			inline:true,
			format:'d-m-Y',
			timepicker:false,
			min:'16-07-2015', // yesterday is minimum date
			max:'30-08-2015' // and tommorow is maximum date calendar
		})
    );
});

What i am doing wrong.

Thanks in advance

**Comment by nazar-pc** [comment]
1. You are not formatting code here, it is not readable
2. You need to separate initialization and getting date with `get_date` method, probably you can initialize it on input and get what you want right there
