### ISSUE TITLE
Month view error with more than one calendar

### ISSUE THREAD

**Issue by innertrends** [nazar-pc/PickMeUp#85]
When using the following setup:
$('.3-mcalendars').pickmeup({
    flat: true,
    date: [
      new Date,
      new Date
    ],
    mode: 'range',
    calendars: 3,
    select_day: false,
    view: 'months'
  });

We found 2 errors:

- You can't select a month from the first calendar. It selects automatically one from the second.

- When using the change callback,
change: function (interval) {
    console.log(interval);
   	}
it returns always the first day of the month. I believe "to" should be the last day of the month.

You can preview both errors here: http://codepen.io/padicode/pen/LVMwNN

**Comment by nazar-pc** [comment]
> You can't select a month from the first calendar. It selects automatically one from the second.
It selects proper date and scrolls calendar to put selected date into center, see #41 and #79

> it returns always the first day of the month. I believe "to" should be the last day of the month.
It returns what it was designed to, you can post-process it as you like afterwards.

**Comment by innertrends** [comment]
Thank you for the reply.
I've seen #41 and #79 but alignment:static does not seem to work for view:month. Am i doing something wrong?

**Comment by nazar-pc** [comment]
Did you try patched version from PR? If so - add a comment there so that PR author can update it.

**Comment by innertrends** [comment]
Are you referring to this: https://github.com/EHLOVader/PickMeUp/tree/calendar-alignment ?
If yes, I tried and it did not work.
Couldn't find a way to write to the author.
I also don't know what PR stands for.
Thank you.

**Comment by nazar-pc** [comment]
PR stands for pull request, in this case #79 is what I was talking about, just write a comment there.

**Comment by innertrends** [comment]
Thank you. I'll do that.

**Comment by nazar-pc** [comment]
Should already be fixed in master branch, test it, please, before I release new version.
