### ISSUE TITLE
How can I make Check -in Check-out

### ISSUE THREAD

**Issue by HelmsArt** [nazar-pc/PickMeUp#87]
Hello, thanks to you for this plugin.
I want to make a check-in check-out date system with this plugin.

I put datepicker to in a div 
I want to make when I select first date, a span will dynamicly get to date, and then I will select second date, another span will dynamicly get to date and datepicker will close.

But I can't do anything when datepicker selected. Can you help me ?
Sory for my english :)

my codes:

```html
<div class="col-xs-8 mt10" class="" id="dp1"></div>
<span id="IndexV3AramaGirisTrh">
</span>
<span id="IndexV3AramaCikisTrh">
</span>
```
```javascript
var BuGun   = new Date;
BuGun.addDays(2);

var DefCheckOut = new Date;
DefCheckOut.addDays(4);
    
$('.1-calendars').pickmeup({
format  : 'd-m-Y',
min         : BuGun,
flat        : true,
date        : [
   BuGun,
   DefCheckOut
],
mode        : 'range',
calendars   : 2
});
```

**Comment by nazar-pc** [comment]
You just need to handle `change` event and update your `span`'s accordingly.
Please refer to readme for details: https://github.com/nazar-pc/PickMeUp#events-callbacks

**Comment by HelmsArt** [comment]
I tried to use to "change" event. But I think used wrong. Can you show to me an example for that how to use.

**Comment by nazar-pc** [comment]
```javascript
$(..).pickmeup({
...
    change : function (formatted_date) {}
...
});
```

**Comment by HelmsArt** [comment]
Nazar you are great. Thanks. I have just final question... I get dates when select datepicker. But I get two dates. For example ; At first selection, I get  '13-08-2015, 13-08-2015' and then at second selection, I get '13-08-2015, 21-08-2015' 

That is become because of the mode is "range". I tried to use "separator" event. But I didn't do it. Can you show to me that how can I get first and second dates separately.

Thanks again for your help.

**Comment by nazar-pc** [comment]
`separator` is not an event. you should be getting array of two dates, but if you print it - it shows like coma-separated, try to print `formatted_date[0]` and `formatted_date[1]` separately.

**Comment by HelmsArt** [comment]
Yes I will print first date to a <span> and print second date to another <span>.
But when I try to do this that like you said, it give me this: 
CODES:
change : function (formatted_date) {            
  var GirisTrh = ($('#dp1').pickmeup('get_date',formatted_date[0]));
  $('#IndexV3AramaGirisTrh').html(GirisTrh);  
}
PRINT:
first select        - 14-08-201514-08-2015 
second select  - 14-08-201514-08-2015 

So it is same data. Do you think I need to convert to string that GirisTrh and use substr

**Comment by nazar-pc** [comment]
WTF is `($('#dp1').pickmeup('get_date',formatted_date[0]))`?
You already have first date in `formatted_date[0]`, just use it directly.

**Comment by HelmsArt** [comment]
I mean this:

(https://cloud.githubusercontent.com/assets/10242641/9115038/b14a75a6-3c65-11e5-8a75-bb6c2f4a878f.jpg)

I can get first and second dates when I selected. But it is printing dates twice like img

**Comment by nazar-pc** [comment]
Printing is something specific your code, if you can get two dates separately - everything further is not PickMeUp's responsibility.
Read the docs and you'll find your answer.
