### ISSUE TITLE
Disable Question

### ISSUE THREAD

**Issue by KhanToruk** [nazar-pc/PickMeUp#88]
Hello,
How can we disable dates which comes before our selected date with in change event ?

**Comment by nazar-pc** [comment]
`render` event allows you to disable arbitrary dates, just check whether date is before selected.

**Comment by KhanToruk** [comment]
thank you. this is so good.

**Comment by KhanToruk** [comment]
Hello again nazar. can we disable days that not in month with a short way?

**Comment by nazar-pc** [comment]
There are only min/max options, you can try to hack that in runtime with `$('...').data('pickmeup-options')`, but inverse is not possible in any easier way. There are many edge cases, so I decided just add universal method for that.
