### ISSUE TITLE
No default_date for 'range' and 'multiple' mode

### ISSUE THREAD

**Issue by Cadaveri13** [nazar-pc/PickMeUp#89]
It was requested a while back that an option to set no default date upon initialization would be added. It seemed to be fixed with default_date : false; hovewer, this option doesn't work with mode : 'range' and 'multiple'.

**Comment by nazar-pc** [comment]
Can you make simple reproducing on jsfiddle, please? There is sample in readme, just modify it to reproduce issue.

**Comment by Cadaveri13** [comment]
Here you go
https://jsfiddle.net/Cadaveri13/z4fmvuzb/130/

**Comment by nazar-pc** [comment]
Thanks, this is definitely a bug.
Feel free to send pull request if you'll fix it.
This feature was implemented by other developer, he likely implemented it for `single` mode only.

**Comment by nazar-pc** [comment]
Should be fixed in 42fb674
