### ISSUE TITLE
Mobile scroll on flat mode

### ISSUE THREAD

**Issue by VincentGarreau** [nazar-pc/PickMeUp#91]
Hi @nazar-pc ! Love this plugin, nice job!
I work on a responsive website (cf image), and unfortunately i can't scroll when i touch the calendar. It would be great if we could :)

<img width="200" alt="capture d ecran 2015-09-10 a 15 23 24" src="https://cloud.githubusercontent.com/assets/961898/9789611/732d47b2-57d1-11e5-8bf4-02251d77f3ad.png">

Great work and thank you.

**Comment by nazar-pc** [comment]
Touch events are not supported as such.
Do you mean swipe or touching arrows?
Touching arrows should work fine, also you can listen to swipes with any other library and call `prev` and `next` methods manually.

**Comment by VincentGarreau** [comment]
Thanks for your quick reply.
Oh ok, i mean when i scroll down on the page (not swipping between the months). So it is a bit problematic :/ So yes, this a touch event.
Arrows and touching dates work fine.

**Comment by nazar-pc** [comment]
https://github.com/nazar-pc/PickMeUp/blob/master/js/jquery.pickmeup.js#L72
Try to specify `trigger_event` option during initialization with just `click` value. It will make clicks on mobile work with 300ms delay, but should not prevent scrolling.

**Comment by nazar-pc** [comment]
Ideally there should be support for `tap` instead of just `touchstart`, but there are not such raw event and implementation would become significantly more complex.

**Comment by VincentGarreau** [comment]
I tried to set a "click" value, but it's not work unfortunately.
Thanks for your help.

**Comment by nazar-pc** [comment]
No, scrolling should work, it is more complex to implement proper touch event handling (but not impossible).
Can you prepare some demo? There is example in readme, you can just modify it with your case so that I can reproduce it.

**Comment by VincentGarreau** [comment]
Yep, the demo: http://devserver.me/pickmeup

I set the "click" event for the single calendar (http://devserver.me/pickmeup/js/demo.js, line 5)
I tried on iPhone 6, iOS 8, last Safari.

Archive demo: http://cl.ly/d3eE

Thanks!

**Comment by nazar-pc** [comment]
Well, that option for whatever reason is not used everywhere.
Basically, just look through the code and remove all `touchstart` mentions.

**Comment by VincentGarreau** [comment]
I remove all touchstart mentions and it works! Thanks ;)

**Comment by nazar-pc** [comment]
PR to actually fix it is also welcomed:)

**Comment by nazar-pc** [comment]
I've added to readme recommended way to handle touch events properly: https://github.com/nazar-pc/PickMeUp#touch-devices
You can try it with just released 2.9.1
