### ISSUE TITLE
October View works improperly on Firefox 40.0.3

### ISSUE THREAD

**Issue by TenenteDan** [nazar-pc/PickMeUp#93]
Hi everybody.

I'm having a problem with October month on IE and Firefox 40.0.3.

When I start the JSFiddle, the 3-calendar view on October has two 17 days. As you can see on image below.

Firefox (http://jsfiddle.net/z4fmvuzb/)
![image](https://cloud.githubusercontent.com/assets/14568039/9993402/f9e56788-604d-11e5-8020-2def2b5b41e9.png)

If I select September, 18th, October starts to show normally, but when I click on other day, October crashes again.

It happens when I change to only one calendar view too.

Could you fix this? Thanks.

**Comment by nazar-pc** [comment]
There is no such issue in Firefox on Linux. Which means that you likely have outdated version of Windows with buggy patch applied (there was such an issue with RTZ 2 at least). It was discussed already even in this repository and have known fixes (the best one is just to install latest updates to buggy Windows version).
Look here for details:
* https://github.com/nazar-pc/PickMeUp/issues/42
* https://github.com/nazar-pc/PickMeUp/issues/47

(some comments in Russian)
