### ISSUE TITLE
Using plugin via bower + webpack make an error

### ISSUE THREAD

**Issue by yazonnile** [nazar-pc/PickMeUp#95]
Hi, there)
I`m using this plugin with bower + webpack
```javascript
require('pickmeup');
```
And this throw an error 
```javascript
Uncaught Error: Cannot find module "./css/pickmeup.css"
```

I`ve fixed it via removing 
```
"css/pickmeup.css"
```
this string from pickmeup/bower.json file
And its work for me.
But Im not sure, that Its a best solution, so plz look on it)

**Comment by nazar-pc** [comment]
I'm not using PickMeUp personally in such setup, PR would be welcomed (but removing "css/pickmeup.css", probably, is not the best idea).

**Comment by yazonnile** [comment]
ha!
As it turned out, its my issue, that comes coz css-loader missing in webpack
But I dont need such a loader, so for the now I just remove that string,

So at all - there is no such an issue.
Sory for disturb
