### ISSUE TITLE
Запрет выбора определенных дат

### ISSUE THREAD

**Issue by skull3d** [nazar-pc/PickMeUp#96]
Подскажите пожалуйста кодом, как добавить disable к датам из массива (запретить их выбор):
http://jsfiddle.net/skull3d/qt107t0o/3/

Понял что надо использовать render, но как конкретно разобраться не могу.

**Comment by nazar-pc** [comment]
Вопросы здесь задают на английском, чтобы остальные могли понять и использовать ответ
https://jsfiddle.net/qt107t0o/4/
