### ISSUE TITLE
Default default_date gets selected even if it falls outside the accebtable date range

### ISSUE THREAD

**Issue by whYME953** [nazar-pc/PickMeUp#97]
If I set the "max" to yesterday (for example,) today's date will still populate the select when the picker opens even though it's outside the acceptable range.

I imagine this is also a problem when default date is set by the user, but presumably in that case they'd make sure to set a valid default_date.

**Comment by nazar-pc** [comment]
Would you be so kind to prepare demo on JsFiddle/JsBin?

**Comment by whYME953** [comment]
http://jsfiddle.net/7fy1d25s/

When no default_date is set or an invalid date is set, it won't let you "select" the date, but it'll put the default in the input field.

as long as there's a valid default_date set there's no problem.

**Comment by nazar-pc** [comment]
This bug should be addressed in a6f74a8: https://jsfiddle.net/7fy1d25s/2/
Could you try build from master branch before I release it (there was quite a lot changes)?
